begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|pdfbox
operator|.
name|cos
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|OutputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|DecimalFormat
import|;
end_import

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|DecimalFormatSymbols
import|;
end_import

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|NumberFormat
import|;
end_import

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|exceptions
operator|.
name|COSVisitorException
import|;
end_import

begin_comment
comment|/**  * This class represents a floating point number in a PDF document.  *  * @author<a href="mailto:ben@benlitchfield.com">Ben Litchfield</a>  * @version $Revision: 1.17 $  */
end_comment

begin_class
specifier|public
class|class
name|COSFloat
extends|extends
name|COSNumber
block|{
specifier|private
name|float
name|value
decl_stmt|;
comment|/**      * Constructor.      *      * @param aFloat The primitive float object that this object wraps.      */
specifier|public
name|COSFloat
parameter_list|(
name|float
name|aFloat
parameter_list|)
block|{
name|value
operator|=
name|aFloat
expr_stmt|;
block|}
comment|/**      * Constructor.      *      * @param aFloat The primitive float object that this object wraps.      *      * @throws IOException If aFloat is not a float.      */
specifier|public
name|COSFloat
parameter_list|(
name|String
name|aFloat
parameter_list|)
throws|throws
name|IOException
block|{
try|try
block|{
name|value
operator|=
name|Float
operator|.
name|parseFloat
argument_list|(
name|aFloat
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Error expected floating point number actual='"
operator|+
name|aFloat
operator|+
literal|"'"
argument_list|)
throw|;
block|}
block|}
comment|/**      * Set the value of the float object.      *      * @param floatValue The new float value.      */
specifier|public
name|void
name|setValue
parameter_list|(
name|float
name|floatValue
parameter_list|)
block|{
name|value
operator|=
name|floatValue
expr_stmt|;
block|}
comment|/**      * The value of the float object that this one wraps.      *      * @return The value of this object.      */
specifier|public
name|float
name|floatValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
comment|/**      * The value of the double object that this one wraps.      *      * @return The double of this object.      */
specifier|public
name|double
name|doubleValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
comment|/**      * This will get the integer value of this object.      *      * @return The int value of this object,      */
specifier|public
name|long
name|longValue
parameter_list|()
block|{
return|return
operator|(
name|long
operator|)
name|value
return|;
block|}
comment|/**      * This will get the integer value of this object.      *      * @return The int value of this object,      */
specifier|public
name|int
name|intValue
parameter_list|()
block|{
return|return
operator|(
name|int
operator|)
name|value
return|;
block|}
comment|/**      * {@inheritDoc}      */
specifier|public
name|boolean
name|equals
parameter_list|(
name|Object
name|o
parameter_list|)
block|{
return|return
name|o
operator|instanceof
name|COSFloat
operator|&&
name|Float
operator|.
name|floatToIntBits
argument_list|(
operator|(
operator|(
name|COSFloat
operator|)
name|o
operator|)
operator|.
name|value
argument_list|)
operator|==
name|Float
operator|.
name|floatToIntBits
argument_list|(
name|value
argument_list|)
return|;
block|}
comment|/**      * {@inheritDoc}      */
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
return|return
name|Float
operator|.
name|floatToIntBits
argument_list|(
name|value
argument_list|)
return|;
block|}
comment|/**      * {@inheritDoc}      */
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"COSFloat{"
operator|+
name|value
operator|+
literal|"}"
return|;
block|}
comment|/**      * visitor pattern double dispatch method.      *      * @param visitor The object to notify when visiting this object.      * @return any object, depending on the visitor implementation, or null      * @throws COSVisitorException If an error occurs while visiting this object.      */
specifier|public
name|Object
name|accept
parameter_list|(
name|ICOSVisitor
name|visitor
parameter_list|)
throws|throws
name|COSVisitorException
block|{
return|return
name|visitor
operator|.
name|visitFromFloat
argument_list|(
name|this
argument_list|)
return|;
block|}
comment|/**      * This will output this string as a PDF object.      *      * @param output The stream to write to.      * @throws IOException If there is an error writing to the stream.      */
specifier|public
name|void
name|writePDF
parameter_list|(
name|OutputStream
name|output
parameter_list|)
throws|throws
name|IOException
block|{
name|DecimalFormat
name|formatDecimal
init|=
operator|(
name|DecimalFormat
operator|)
name|NumberFormat
operator|.
name|getNumberInstance
argument_list|()
decl_stmt|;
name|formatDecimal
operator|.
name|setMaximumFractionDigits
argument_list|(
literal|10
argument_list|)
expr_stmt|;
name|formatDecimal
operator|.
name|setGroupingUsed
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|DecimalFormatSymbols
name|symbols
init|=
name|formatDecimal
operator|.
name|getDecimalFormatSymbols
argument_list|()
decl_stmt|;
name|symbols
operator|.
name|setDecimalSeparator
argument_list|(
literal|'.'
argument_list|)
expr_stmt|;
name|formatDecimal
operator|.
name|setDecimalFormatSymbols
argument_list|(
name|symbols
argument_list|)
expr_stmt|;
name|output
operator|.
name|write
argument_list|(
name|formatDecimal
operator|.
name|format
argument_list|(
name|value
argument_list|)
operator|.
name|getBytes
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

