begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|xobject
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|AlphaComposite
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Color
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Graphics2D
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|BufferedImage
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileOutputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|OutputStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|Log
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|LogFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSArray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
operator|.
name|PDStream
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDColorSpace
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDColorSpaceFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDColorState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDDeviceGray
import|;
end_import

begin_comment
comment|/**  * The prototype for all PDImages.  *  * @author<a href="mailto:ben@benlitchfield.com">Ben Litchfield</a>  * @author mathiak  */
end_comment

begin_class
specifier|public
specifier|abstract
class|class
name|PDXObjectImage
extends|extends
name|PDXObject
block|{
comment|/**      * Log instance.      */
specifier|private
specifier|static
specifier|final
name|Log
name|LOG
init|=
name|LogFactory
operator|.
name|getLog
argument_list|(
name|PDXObjectImage
operator|.
name|class
argument_list|)
decl_stmt|;
comment|/**      * The XObject subtype.      */
specifier|public
specifier|static
specifier|final
name|String
name|SUB_TYPE
init|=
literal|"Image"
decl_stmt|;
comment|/**      * This contains the suffix used when writing to file.      */
specifier|private
name|String
name|suffix
decl_stmt|;
specifier|private
name|PDColorState
name|stencilColor
decl_stmt|;
comment|/**      * Standard constructor.      *      * @param imageStream The XObject is passed as a COSStream.      * @param fileSuffix The file suffix, jpg/png.      */
specifier|public
name|PDXObjectImage
parameter_list|(
name|PDStream
name|imageStream
parameter_list|,
name|String
name|fileSuffix
parameter_list|)
block|{
name|super
argument_list|(
name|imageStream
argument_list|)
expr_stmt|;
name|suffix
operator|=
name|fileSuffix
expr_stmt|;
block|}
comment|/**      * Standard constructor.      *      * @param doc The document to store the stream in.      * @param fileSuffix The file suffix, jpg/png.      */
specifier|public
name|PDXObjectImage
parameter_list|(
name|PDDocument
name|doc
parameter_list|,
name|String
name|fileSuffix
parameter_list|)
block|{
name|super
argument_list|(
name|doc
argument_list|)
expr_stmt|;
name|getCOSStream
argument_list|()
operator|.
name|setName
argument_list|(
name|COSName
operator|.
name|SUBTYPE
argument_list|,
name|SUB_TYPE
argument_list|)
expr_stmt|;
name|suffix
operator|=
name|fileSuffix
expr_stmt|;
block|}
comment|/**      * Create the correct thumbnail from the cos base.      *      * @param xobject The cos level xobject to create.      *      * @return a pdmodel xobject      * @throws IOException If there is an error creating the xobject.      */
specifier|public
specifier|static
name|PDXObject
name|createThumbnailXObject
parameter_list|(
name|COSBase
name|xobject
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|commonXObjectCreation
argument_list|(
name|xobject
argument_list|,
literal|true
argument_list|,
literal|null
argument_list|)
return|;
block|}
comment|/**      * Returns an java.awt.Image, that can be used for display etc.      *      * @return This PDF object as an AWT image.      *      * @throws IOException If there is an error creating the image.      */
specifier|public
specifier|abstract
name|BufferedImage
name|getRGBImage
parameter_list|()
throws|throws
name|IOException
function_decl|;
comment|/**      * Returns a PDXObjectImage of the SMask image, if there is one.      * See section 11.5 of the pdf specification for details on Soft Masks.      *      * @return the PDXObjectImage of the SMask if there is one, else<code>null</code>.      * @throws IOException if an I/O error occurs creating an XObject      */
specifier|public
name|PDXObjectImage
name|getSMaskImage
parameter_list|()
throws|throws
name|IOException
block|{
name|COSStream
name|cosStream
init|=
name|getPDStream
argument_list|()
operator|.
name|getStream
argument_list|()
decl_stmt|;
name|COSBase
name|smask
init|=
name|cosStream
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|SMASK
argument_list|)
decl_stmt|;
if|if
condition|(
name|smask
operator|==
literal|null
condition|)
block|{
return|return
literal|null
return|;
block|}
else|else
block|{
return|return
operator|(
name|PDXObjectImage
operator|)
name|PDXObject
operator|.
name|createXObject
argument_list|(
name|smask
argument_list|)
return|;
block|}
block|}
comment|/**      * Add masked image to the given image.      *       * @param baseImage the base image.      * @return the masked image.      * @throws IOException if something went wrong      */
specifier|protected
name|BufferedImage
name|applyMasks
parameter_list|(
name|BufferedImage
name|baseImage
parameter_list|)
throws|throws
name|IOException
block|{
if|if
condition|(
name|getImageMask
argument_list|()
condition|)
block|{
return|return
name|imageMask
argument_list|(
name|baseImage
argument_list|)
return|;
block|}
if|if
condition|(
name|getMask
argument_list|()
operator|!=
literal|null
condition|)
block|{
return|return
name|mask
argument_list|(
name|baseImage
argument_list|)
return|;
block|}
name|PDXObjectImage
name|smask
init|=
name|getSMaskImage
argument_list|()
decl_stmt|;
if|if
condition|(
name|smask
operator|!=
literal|null
condition|)
block|{
name|BufferedImage
name|smaskBI
init|=
name|smask
operator|.
name|getRGBImage
argument_list|()
decl_stmt|;
if|if
condition|(
name|smaskBI
operator|!=
literal|null
condition|)
block|{
name|COSArray
name|decodeArray
init|=
name|smask
operator|.
name|getDecode
argument_list|()
decl_stmt|;
name|CompositeImage
name|compositeImage
init|=
operator|new
name|CompositeImage
argument_list|(
name|baseImage
argument_list|,
name|smaskBI
argument_list|)
decl_stmt|;
name|BufferedImage
name|rgbImage
init|=
name|compositeImage
operator|.
name|createMaskedImage
argument_list|(
name|decodeArray
argument_list|)
decl_stmt|;
return|return
name|rgbImage
return|;
block|}
else|else
block|{
comment|// this may happen if the smask is somehow broken, e.g. unsupported filter
name|LOG
operator|.
name|warn
argument_list|(
literal|"masking getRGBImage returned NULL"
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|baseImage
return|;
block|}
comment|/**      * Determines is the XObject has any mask.      *       * @return true if the XObkject has any mask      * @throws IOException if something went wrong      */
specifier|protected
name|boolean
name|hasMask
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|getImageMask
argument_list|()
operator|||
name|getMask
argument_list|()
operator|!=
literal|null
operator|||
name|getSMaskImage
argument_list|()
operator|!=
literal|null
return|;
block|}
specifier|private
name|BufferedImage
name|imageMask
parameter_list|(
name|BufferedImage
name|baseImage
parameter_list|)
throws|throws
name|IOException
block|{
name|BufferedImage
name|stencilMask
init|=
operator|new
name|BufferedImage
argument_list|(
name|baseImage
operator|.
name|getWidth
argument_list|()
argument_list|,
name|baseImage
operator|.
name|getHeight
argument_list|()
argument_list|,
name|BufferedImage
operator|.
name|TYPE_INT_ARGB
argument_list|)
decl_stmt|;
name|Graphics2D
name|graphics
init|=
operator|(
name|Graphics2D
operator|)
name|stencilMask
operator|.
name|getGraphics
argument_list|()
decl_stmt|;
if|if
condition|(
name|getStencilColor
argument_list|()
operator|!=
literal|null
condition|)
block|{
name|graphics
operator|.
name|setColor
argument_list|(
name|getStencilColor
argument_list|()
operator|.
name|getJavaColor
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// this might happen when using ExractImages, see PDFBOX-1145
name|LOG
operator|.
name|debug
argument_list|(
literal|"no stencil color for PixelMap found, using Color.BLACK instead."
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setColor
argument_list|(
name|Color
operator|.
name|BLACK
argument_list|)
expr_stmt|;
block|}
name|graphics
operator|.
name|fillRect
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|baseImage
operator|.
name|getWidth
argument_list|()
argument_list|,
name|baseImage
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
comment|// assume default values ([0,1]) for the DecodeArray
comment|// TODO DecodeArray == [1,0]
name|graphics
operator|.
name|setComposite
argument_list|(
name|AlphaComposite
operator|.
name|DstIn
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|drawImage
argument_list|(
name|baseImage
argument_list|,
literal|null
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|dispose
argument_list|()
expr_stmt|;
return|return
name|stencilMask
return|;
block|}
specifier|private
name|BufferedImage
name|mask
parameter_list|(
name|BufferedImage
name|baseImage
parameter_list|)
throws|throws
name|IOException
block|{
name|COSBase
name|mask
init|=
name|getMask
argument_list|()
decl_stmt|;
if|if
condition|(
name|mask
operator|instanceof
name|COSStream
condition|)
block|{
name|PDXObjectImage
name|maskImageRef
init|=
operator|(
name|PDXObjectImage
operator|)
name|PDXObject
operator|.
name|createXObject
argument_list|(
operator|(
name|COSStream
operator|)
name|mask
argument_list|)
decl_stmt|;
name|BufferedImage
name|maskImage
init|=
name|maskImageRef
operator|.
name|getRGBImage
argument_list|()
decl_stmt|;
if|if
condition|(
name|maskImage
operator|==
literal|null
condition|)
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"masking getRGBImage returned NULL"
argument_list|)
expr_stmt|;
return|return
name|baseImage
return|;
block|}
name|BufferedImage
name|newImage
init|=
operator|new
name|BufferedImage
argument_list|(
name|maskImage
operator|.
name|getWidth
argument_list|()
argument_list|,
name|maskImage
operator|.
name|getHeight
argument_list|()
argument_list|,
name|BufferedImage
operator|.
name|TYPE_INT_ARGB
argument_list|)
decl_stmt|;
name|Graphics2D
name|graphics
init|=
operator|(
name|Graphics2D
operator|)
name|newImage
operator|.
name|getGraphics
argument_list|()
decl_stmt|;
name|graphics
operator|.
name|drawImage
argument_list|(
name|baseImage
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|maskImage
operator|.
name|getWidth
argument_list|()
argument_list|,
name|maskImage
operator|.
name|getHeight
argument_list|()
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
name|baseImage
operator|.
name|getWidth
argument_list|()
argument_list|,
name|baseImage
operator|.
name|getHeight
argument_list|()
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setComposite
argument_list|(
name|AlphaComposite
operator|.
name|DstIn
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|drawImage
argument_list|(
name|maskImage
argument_list|,
literal|null
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|dispose
argument_list|()
expr_stmt|;
return|return
name|newImage
return|;
block|}
else|else
block|{
comment|// TODO Colour key masking
name|LOG
operator|.
name|warn
argument_list|(
literal|"Colour key masking isn't supported"
argument_list|)
expr_stmt|;
return|return
name|baseImage
return|;
block|}
block|}
comment|/**      * Writes the Image to out.      * @param out the OutputStream that the Image is written to.      * @throws IOException when somethings wrong with out      */
specifier|public
specifier|abstract
name|void
name|write2OutputStream
parameter_list|(
name|OutputStream
name|out
parameter_list|)
throws|throws
name|IOException
function_decl|;
comment|/**      * Writes the image to a file with the filename + an appropriate suffix, like "Image.jpg".      * The suffix is automatically set by the      * @param filename the filename      * @throws IOException When somethings wrong with the corresponding file.      */
specifier|public
name|void
name|write2file
parameter_list|(
name|String
name|filename
parameter_list|)
throws|throws
name|IOException
block|{
name|FileOutputStream
name|out
init|=
literal|null
decl_stmt|;
try|try
block|{
name|out
operator|=
operator|new
name|FileOutputStream
argument_list|(
name|filename
operator|+
literal|"."
operator|+
name|suffix
argument_list|)
expr_stmt|;
name|write2OutputStream
argument_list|(
name|out
argument_list|)
expr_stmt|;
name|out
operator|.
name|flush
argument_list|()
expr_stmt|;
block|}
finally|finally
block|{
if|if
condition|(
name|out
operator|!=
literal|null
condition|)
block|{
name|out
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
comment|/**      * Writes the image to a file with the filename + an appropriate      * suffix, like "Image.jpg".      * The suffix is automatically set by the      * @param file the file      * @throws IOException When somethings wrong with the corresponding file.      */
specifier|public
name|void
name|write2file
parameter_list|(
name|File
name|file
parameter_list|)
throws|throws
name|IOException
block|{
name|FileOutputStream
name|out
init|=
literal|null
decl_stmt|;
try|try
block|{
name|out
operator|=
operator|new
name|FileOutputStream
argument_list|(
name|file
argument_list|)
expr_stmt|;
name|write2OutputStream
argument_list|(
name|out
argument_list|)
expr_stmt|;
name|out
operator|.
name|flush
argument_list|()
expr_stmt|;
block|}
finally|finally
block|{
if|if
condition|(
name|out
operator|!=
literal|null
condition|)
block|{
name|out
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
comment|/**      * Get the height of the image.      *      * @return The height of the image.      */
specifier|public
name|int
name|getHeight
parameter_list|()
block|{
return|return
name|getCOSStream
argument_list|()
operator|.
name|getInt
argument_list|(
name|COSName
operator|.
name|HEIGHT
argument_list|,
operator|-
literal|1
argument_list|)
return|;
block|}
comment|/**      * Set the height of the image.      *      * @param height The height of the image.      */
specifier|public
name|void
name|setHeight
parameter_list|(
name|int
name|height
parameter_list|)
block|{
name|getCOSStream
argument_list|()
operator|.
name|setInt
argument_list|(
name|COSName
operator|.
name|HEIGHT
argument_list|,
name|height
argument_list|)
expr_stmt|;
block|}
comment|/**      * Get the width of the image.      *      * @return The width of the image.      */
specifier|public
name|int
name|getWidth
parameter_list|()
block|{
return|return
name|getCOSStream
argument_list|()
operator|.
name|getInt
argument_list|(
name|COSName
operator|.
name|WIDTH
argument_list|,
operator|-
literal|1
argument_list|)
return|;
block|}
comment|/**      * Set the width of the image.      *      * @param width The width of the image.      */
specifier|public
name|void
name|setWidth
parameter_list|(
name|int
name|width
parameter_list|)
block|{
name|getCOSStream
argument_list|()
operator|.
name|setInt
argument_list|(
name|COSName
operator|.
name|WIDTH
argument_list|,
name|width
argument_list|)
expr_stmt|;
block|}
comment|/**      * The bits per component of this image.  This will return -1 if one has not      * been set.      *      * @return The number of bits per component.      */
specifier|public
name|int
name|getBitsPerComponent
parameter_list|()
block|{
return|return
name|getCOSStream
argument_list|()
operator|.
name|getInt
argument_list|(
name|COSName
operator|.
name|BITS_PER_COMPONENT
argument_list|,
name|COSName
operator|.
name|BPC
argument_list|,
operator|-
literal|1
argument_list|)
return|;
block|}
comment|/**      * Set the number of bits per component.      *      * @param bpc The number of bits per component.      */
specifier|public
name|void
name|setBitsPerComponent
parameter_list|(
name|int
name|bpc
parameter_list|)
block|{
name|getCOSStream
argument_list|()
operator|.
name|setInt
argument_list|(
name|COSName
operator|.
name|BITS_PER_COMPONENT
argument_list|,
name|bpc
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the color space or null if none exists.      *      * @return The color space for this image.      *      * @throws IOException If there is an error getting the colorspace.      */
specifier|public
name|PDColorSpace
name|getColorSpace
parameter_list|()
throws|throws
name|IOException
block|{
name|COSBase
name|cs
init|=
name|getCOSStream
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|COLORSPACE
argument_list|,
name|COSName
operator|.
name|CS
argument_list|)
decl_stmt|;
name|PDColorSpace
name|retval
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|cs
operator|!=
literal|null
condition|)
block|{
name|retval
operator|=
name|PDColorSpaceFactory
operator|.
name|createColorSpace
argument_list|(
name|cs
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|==
literal|null
condition|)
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"About to return NULL from createColorSpace branch"
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
comment|// there are some cases where the 'required' CS value is not present
comment|// but we know that it will be grayscale for a CCITT filter.
name|COSBase
name|filter
init|=
name|getCOSStream
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|FILTER
argument_list|)
decl_stmt|;
if|if
condition|(
name|COSName
operator|.
name|CCITTFAX_DECODE
operator|.
name|equals
argument_list|(
name|filter
argument_list|)
operator|||
name|COSName
operator|.
name|CCITTFAX_DECODE_ABBREVIATION
operator|.
name|equals
argument_list|(
name|filter
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDDeviceGray
argument_list|()
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|COSName
operator|.
name|JBIG2_DECODE
operator|.
name|equals
argument_list|(
name|filter
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDDeviceGray
argument_list|()
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|getImageMask
argument_list|()
condition|)
block|{
comment|// image is a stencil mask -> use DeviceGray
name|retval
operator|=
operator|new
name|PDDeviceGray
argument_list|()
expr_stmt|;
block|}
else|else
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"About to return NULL from unhandled branch."
operator|+
literal|" filter = "
operator|+
name|filter
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|retval
return|;
block|}
comment|/**      * This will set the color space for this image.      *      * @param cs The color space for this image.      */
specifier|public
name|void
name|setColorSpace
parameter_list|(
name|PDColorSpace
name|cs
parameter_list|)
block|{
name|COSBase
name|base
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|cs
operator|!=
literal|null
condition|)
block|{
name|base
operator|=
name|cs
operator|.
name|getCOSObject
argument_list|()
expr_stmt|;
block|}
name|getCOSStream
argument_list|()
operator|.
name|setItem
argument_list|(
name|COSName
operator|.
name|COLORSPACE
argument_list|,
name|base
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the suffix for this image type, jpg/png.      *      * @return The image suffix.      */
specifier|public
name|String
name|getSuffix
parameter_list|()
block|{
return|return
name|suffix
return|;
block|}
comment|/**      * Get the ImageMask flag. Used in Stencil Masking.  Section 4.8.5 of the spec.      *      * @return The ImageMask flag.  This is optional and defaults to False, so if it does not exist, we return False      */
specifier|public
name|boolean
name|getImageMask
parameter_list|()
block|{
return|return
name|getCOSStream
argument_list|()
operator|.
name|getBoolean
argument_list|(
name|COSName
operator|.
name|IMAGE_MASK
argument_list|,
literal|false
argument_list|)
return|;
block|}
comment|/**      * Set the current non stroking colorstate. It'll be used to create stencil masked images.      *       * @param stencilColorValue The non stroking colorstate      */
specifier|public
name|void
name|setStencilColor
parameter_list|(
name|PDColorState
name|stencilColorValue
parameter_list|)
block|{
name|stencilColor
operator|=
name|stencilColorValue
expr_stmt|;
block|}
comment|/**      * Returns the non stroking colorstate to be used to create stencil makes images.      *       * @return The current non stroking colorstate.      */
specifier|public
name|PDColorState
name|getStencilColor
parameter_list|()
block|{
return|return
name|stencilColor
return|;
block|}
comment|/**      * Returns the Decode Array of an XObjectImage.      * @return the decode array      */
specifier|public
name|COSArray
name|getDecode
parameter_list|()
block|{
name|COSBase
name|decode
init|=
name|getCOSStream
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|DECODE
argument_list|)
decl_stmt|;
if|if
condition|(
name|decode
operator|!=
literal|null
operator|&&
name|decode
operator|instanceof
name|COSArray
condition|)
block|{
return|return
operator|(
name|COSArray
operator|)
name|decode
return|;
block|}
return|return
literal|null
return|;
block|}
comment|/**      * Returns the optional mask of a XObjectImage if there is one.      *      * @return The mask otherwise null.      */
specifier|public
name|COSBase
name|getMask
parameter_list|()
block|{
name|COSBase
name|mask
init|=
name|getCOSStream
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|MASK
argument_list|)
decl_stmt|;
if|if
condition|(
name|mask
operator|!=
literal|null
condition|)
block|{
return|return
name|mask
return|;
block|}
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

