begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|form
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDFont
import|;
end_import

begin_class
class|class
name|AppearanceStyle
block|{
specifier|private
specifier|static
specifier|final
name|float
name|FONTSCALE
init|=
literal|1000f
decl_stmt|;
specifier|private
name|PDFont
name|font
decl_stmt|;
specifier|private
name|float
name|fontSize
decl_stmt|;
specifier|private
name|float
name|leading
decl_stmt|;
name|PDFont
name|getFont
parameter_list|()
block|{
return|return
name|font
return|;
block|}
name|void
name|setFont
parameter_list|(
name|PDFont
name|font
parameter_list|)
block|{
name|this
operator|.
name|font
operator|=
name|font
expr_stmt|;
block|}
name|float
name|getFontSize
parameter_list|()
block|{
return|return
name|fontSize
return|;
block|}
name|void
name|setFontSize
parameter_list|(
name|float
name|fontSize
parameter_list|)
block|{
specifier|final
name|float
name|scale
init|=
name|fontSize
operator|/
name|FONTSCALE
decl_stmt|;
name|this
operator|.
name|fontSize
operator|=
name|fontSize
expr_stmt|;
if|if
condition|(
name|leading
operator|==
literal|0
condition|)
block|{
try|try
block|{
name|leading
operator|=
name|font
operator|.
name|getBoundingBox
argument_list|()
operator|.
name|getHeight
argument_list|()
operator|*
name|scale
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|e
parameter_list|)
block|{
name|leading
operator|=
name|fontSize
operator|*
literal|1.2f
expr_stmt|;
block|}
block|}
block|}
name|float
name|getLeading
parameter_list|()
block|{
return|return
name|leading
return|;
block|}
name|void
name|setLeading
parameter_list|(
name|float
name|leading
parameter_list|)
block|{
name|this
operator|.
name|leading
operator|=
name|leading
expr_stmt|;
block|}
block|}
end_class

end_unit

