begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|fontbox
operator|.
name|ttf
operator|.
name|model
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|fontbox
operator|.
name|ttf
operator|.
name|gsub
operator|.
name|GsubWorker
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|fontbox
operator|.
name|ttf
operator|.
name|gsub
operator|.
name|GsubWorkerFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|fontbox
operator|.
name|ttf
operator|.
name|table
operator|.
name|common
operator|.
name|ScriptRecord
import|;
end_import

begin_comment
comment|/**  * Enumerates the languages supported for GSUB operation. In order to support a new language, you  * need to add it here and then implement the {@link GsubWorker} for the given language and return  * the same from the  * {@link GsubWorkerFactory#getGsubWorker(org.apache.fontbox.ttf.CmapLookup, GsubData)}  *  * @author Palash Ray  *  */
end_comment

begin_enum
specifier|public
enum|enum
name|Language
block|{
name|BENGALI
argument_list|(
operator|new
name|String
index|[]
block|{
literal|"bng2"
block|,
literal|"beng"
block|}
argument_list|)
block|;
specifier|private
specifier|final
name|String
index|[]
name|scriptNames
decl_stmt|;
specifier|private
name|Language
parameter_list|(
name|String
index|[]
name|scriptNames
parameter_list|)
block|{
name|this
operator|.
name|scriptNames
operator|=
name|scriptNames
expr_stmt|;
block|}
comment|/**      * ScriptNames form the basis of identification of the language. This method gets the ScriptNames that the given      * Language supports, in the order of preference, Index 0 being the most preferred. These names should match the      * {@link ScriptRecord} in the GSUB system.      */
specifier|public
name|String
index|[]
name|getScriptNames
parameter_list|()
block|{
return|return
name|scriptNames
return|;
block|}
block|}
end_enum

end_unit

