begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************************  *   * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *   * http://www.apache.org/licenses/LICENSE-2.0  *   * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  *   ****************************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|action
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|PreflightConstants
operator|.
name|ERROR_ACTION_HIDE_H_INVALID
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|PreflightConstants
operator|.
name|ERROR_ACTION_INVALID_TYPE
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|PreflightConstants
operator|.
name|ERROR_ACTION_MISING_KEY
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSArray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSString
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|PreflightContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|preflight
operator|.
name|ValidationResult
operator|.
name|ValidationError
import|;
end_import

begin_comment
comment|/**  * ActionManager for the Hide action. The Hide action isn't specifically prohibited by PDF/A-1, but should have been. So  * this action manager isn't an instance of InvalidAction but authorized only the H entry with the false value.  */
end_comment

begin_class
specifier|public
class|class
name|HideAction
extends|extends
name|AbstractActionManager
block|{
comment|/**      * @param amFact      *            Instance of ActionManagerFactory used to create ActionManager to check Next actions.      * @param adict      *            the COSDictionary of the action wrapped by this class.      * @param ctx      *            the DocumentHandler from which the action comes from.      * @param aaKey      *            The name of the key which identify the action in a additional action dictionary.      */
specifier|public
name|HideAction
parameter_list|(
name|ActionManagerFactory
name|amFact
parameter_list|,
name|COSDictionary
name|adict
parameter_list|,
name|PreflightContext
name|ctx
parameter_list|,
name|String
name|aaKey
parameter_list|)
block|{
name|super
argument_list|(
name|amFact
argument_list|,
name|adict
argument_list|,
name|ctx
argument_list|,
name|aaKey
argument_list|)
expr_stmt|;
block|}
comment|/*      * (non-Javadoc)      *       * @see org.apache.pdfbox.preflight.action.AbstractActionManager#valid(java.util .List)      */
annotation|@
name|Override
specifier|protected
name|boolean
name|innerValid
parameter_list|()
block|{
name|COSBase
name|t
init|=
name|this
operator|.
name|actionDictionnary
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|T
argument_list|)
decl_stmt|;
comment|// ---- T entry is mandatory
if|if
condition|(
name|t
operator|==
literal|null
condition|)
block|{
name|context
operator|.
name|addValidationError
argument_list|(
operator|new
name|ValidationError
argument_list|(
name|ERROR_ACTION_MISING_KEY
argument_list|,
literal|"T entry is mandatory for the NamedActions"
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
if|if
condition|(
operator|!
operator|(
name|t
operator|instanceof
name|COSDictionary
operator|||
name|t
operator|instanceof
name|COSArray
operator|||
name|t
operator|instanceof
name|COSString
operator|||
name|t
operator|instanceof
name|COSName
operator|)
condition|)
block|{
name|context
operator|.
name|addValidationError
argument_list|(
operator|new
name|ValidationError
argument_list|(
name|ERROR_ACTION_INVALID_TYPE
argument_list|,
literal|"T entry type is invalid"
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
comment|/*          * ---- H entry is optional but the default value is True (annotations of the T entry will be hidden) according          * to the aim of a PDF/A it should be false (annotations of the T entry will be shown).          *           * We check the H value and we throw an error if it is true because of the PDF/A Application Notes sentence :          *           * The PDF Reference supports a concept whereby something will happen when the user performs an explicit or          * implicit action in a PDF viewer - these "things" are called Actions. PDF/A-1 permits a limited set of these          * Actions, which are detailed in section 6.6.1. Specifically, any action that could change the visual          * representation of the document or is not documented in the PDF Reference is not permitted. This includes the          * /Hide action which isn't specifically prohibited by PDF/A-1, but should have been.          */
name|boolean
name|h
init|=
name|this
operator|.
name|actionDictionnary
operator|.
name|getBoolean
argument_list|(
name|COSName
operator|.
name|H
argument_list|,
literal|true
argument_list|)
decl_stmt|;
if|if
condition|(
name|h
condition|)
block|{
name|context
operator|.
name|addValidationError
argument_list|(
operator|new
name|ValidationError
argument_list|(
name|ERROR_ACTION_HIDE_H_INVALID
argument_list|,
literal|"H entry is \"true\""
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|false
return|;
block|}
return|return
literal|true
return|;
block|}
block|}
end_class

end_unit

