begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|Log
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|LogFactory
import|;
end_import

begin_comment
comment|/**  * This will create the correct type of font based on information in the dictionary.  *  * @author<a href="mailto:ben@benlitchfield.com">Ben Litchfield</a>  * @version $Revision: 1.6 $  */
end_comment

begin_class
specifier|public
class|class
name|PDFontFactory
block|{
comment|/**      * private constructor, should only use static methods in this class.      */
specifier|private
name|PDFontFactory
parameter_list|()
block|{     }
comment|/**      * Logger instance.      */
specifier|private
specifier|static
specifier|final
name|Log
name|LOG
init|=
name|LogFactory
operator|.
name|getLog
argument_list|(
name|PDFontFactory
operator|.
name|class
argument_list|)
decl_stmt|;
comment|/**      * This will create the correct font based on information in the dictionary.      *      * @param dic The populated dictionary.      *      * @param fontCache A Map to cache already created fonts      *      * @return The corrent implementation for the font.      *      * @throws IOException If the dictionary is not valid.      *       * @deprecated due to some side effects font caching is no longer supported,       * use {@link #createFont(COSDictionary)} instead      */
specifier|public
specifier|static
name|PDFont
name|createFont
parameter_list|(
name|COSDictionary
name|dic
parameter_list|,
name|Map
name|fontCache
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|createFont
argument_list|(
name|dic
argument_list|)
return|;
block|}
comment|/**      * This will create the correct font based on information in the dictionary.      *      * @param dic The populated dictionary.      *      * @return The corrent implementation for the font.      *      * @throws IOException If the dictionary is not valid.      */
specifier|public
specifier|static
name|PDFont
name|createFont
parameter_list|(
name|COSDictionary
name|dic
parameter_list|)
throws|throws
name|IOException
block|{
name|PDFont
name|retval
init|=
literal|null
decl_stmt|;
name|COSName
name|type
init|=
operator|(
name|COSName
operator|)
name|dic
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|TYPE
argument_list|)
decl_stmt|;
if|if
condition|(
name|type
operator|!=
literal|null
operator|&&
operator|!
name|COSName
operator|.
name|FONT
operator|.
name|equals
argument_list|(
name|type
argument_list|)
condition|)
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Cannot create font if /Type is not /Font.  Actual="
operator|+
name|type
argument_list|)
throw|;
block|}
name|COSName
name|subType
init|=
operator|(
name|COSName
operator|)
name|dic
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|SUBTYPE
argument_list|)
decl_stmt|;
if|if
condition|(
name|subType
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Cannot create font as /SubType is not set."
argument_list|)
throw|;
block|}
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|TYPE1
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDType1Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|MM_TYPE1
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDMMType1Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|TRUE_TYPE
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDTrueTypeFont
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|TYPE3
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDType3Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|TYPE0
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDType0Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|CID_FONT_TYPE0
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDCIDFontType0Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subType
operator|.
name|equals
argument_list|(
name|COSName
operator|.
name|CID_FONT_TYPE2
argument_list|)
condition|)
block|{
name|retval
operator|=
operator|new
name|PDCIDFontType2Font
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|LOG
operator|.
name|warn
argument_list|(
literal|"Substituting TrueType for unknown font subtype="
operator|+
name|subType
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|retval
operator|=
operator|new
name|PDTrueTypeFont
argument_list|(
name|dic
argument_list|)
expr_stmt|;
block|}
return|return
name|retval
return|;
block|}
block|}
end_class

end_unit

