begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|fdf
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|Element
import|;
end_import

begin_comment
comment|/**  * This represents a FreeText FDF annotation.  *  * @author Ben Litchfield  */
end_comment

begin_class
specifier|public
class|class
name|FDFAnnotationFreeText
extends|extends
name|FDFAnnotation
block|{
comment|/**      * COS Model value for SubType entry.      */
specifier|public
specifier|static
specifier|final
name|String
name|SUBTYPE
init|=
literal|"FreeText"
decl_stmt|;
comment|/**      * Default constructor.      */
specifier|public
name|FDFAnnotationFreeText
parameter_list|()
block|{
name|super
argument_list|()
expr_stmt|;
name|annot
operator|.
name|setName
argument_list|(
name|COSName
operator|.
name|SUBTYPE
argument_list|,
name|SUBTYPE
argument_list|)
expr_stmt|;
block|}
comment|/**      * Constructor.      *      * @param a An existing FDF Annotation.      */
specifier|public
name|FDFAnnotationFreeText
parameter_list|(
name|COSDictionary
name|a
parameter_list|)
block|{
name|super
argument_list|(
name|a
argument_list|)
expr_stmt|;
block|}
comment|/**      * Constructor.      *      * @param element An XFDF element.      *      * @throws IOException If there is an error extracting information from the element.      */
specifier|public
name|FDFAnnotationFreeText
parameter_list|(
name|Element
name|element
parameter_list|)
throws|throws
name|IOException
block|{
name|super
argument_list|(
name|element
argument_list|)
expr_stmt|;
name|annot
operator|.
name|setName
argument_list|(
name|COSName
operator|.
name|SUBTYPE
argument_list|,
name|SUBTYPE
argument_list|)
expr_stmt|;
name|setJustification
argument_list|(
name|element
operator|.
name|getAttribute
argument_list|(
literal|"justification"
argument_list|)
argument_list|)
expr_stmt|;
name|String
name|rotation
init|=
name|element
operator|.
name|getAttribute
argument_list|(
literal|"rotation"
argument_list|)
decl_stmt|;
if|if
condition|(
name|rotation
operator|!=
literal|null
operator|&&
operator|!
name|rotation
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|setRotation
argument_list|(
name|Integer
operator|.
name|parseInt
argument_list|(
name|rotation
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * This will set the form of quadding (justification) of the annotation text.      *       * @param justification The quadding of the text.      */
specifier|public
name|void
name|setJustification
parameter_list|(
name|String
name|justification
parameter_list|)
block|{
name|int
name|quadding
init|=
literal|0
decl_stmt|;
if|if
condition|(
literal|"centered"
operator|.
name|equals
argument_list|(
name|justification
argument_list|)
condition|)
block|{
name|quadding
operator|=
literal|1
expr_stmt|;
block|}
elseif|else
if|if
condition|(
literal|"right"
operator|.
name|equals
argument_list|(
name|justification
argument_list|)
condition|)
block|{
name|quadding
operator|=
literal|2
expr_stmt|;
block|}
name|annot
operator|.
name|setInt
argument_list|(
name|COSName
operator|.
name|Q
argument_list|,
name|quadding
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the form of quadding (justification) of the annotation text.      *       * @return The quadding of the text.      */
specifier|public
name|String
name|getJustification
parameter_list|()
block|{
return|return
literal|""
operator|+
name|annot
operator|.
name|getInt
argument_list|(
name|COSName
operator|.
name|Q
argument_list|,
literal|0
argument_list|)
return|;
block|}
comment|/**      * This will set the clockwise rotation in degrees.      *       * @param rotation The number of degrees of clockwise rotation.      */
specifier|public
name|void
name|setRotation
parameter_list|(
name|int
name|rotation
parameter_list|)
block|{
name|annot
operator|.
name|setInt
argument_list|(
name|COSName
operator|.
name|ROTATE
argument_list|,
name|rotation
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the clockwise rotation in degrees.      *       * @return The number of degrees of clockwise rotation.      */
specifier|public
name|String
name|getRotation
parameter_list|()
block|{
return|return
name|annot
operator|.
name|getString
argument_list|(
name|COSName
operator|.
name|ROTATE
argument_list|)
return|;
block|}
block|}
end_class

end_unit

