begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Copyright (c) 2004, www.pdfbox.org  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions are met:  *  * 1. Redistributions of source code must retain the above copyright notice,  *    this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright notice,  *    this list of conditions and the following disclaimer in the documentation  *    and/or other materials provided with the distribution.  * 3. Neither the name of pdfbox; nor the names of its  *    contributors may be used to endorse or promote products derived from this  *    software without specific prior written permission.  *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE  * DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY  * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES  * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;  * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON  * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT  * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  *  * http://www.pdfbox.org  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
package|;
end_package

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_comment
comment|/**  * A named text stream is a combination of a name and a PDTextStream object.  This  * is used in name trees.  *  * @author<a href="mailto:ben@benlitchfield.com">Ben Litchfield</a>  * @version $Revision: 1.3 $  */
end_comment

begin_class
specifier|public
class|class
name|PDNamedTextStream
implements|implements
name|DualCOSObjectable
block|{
specifier|private
name|COSName
name|streamName
decl_stmt|;
specifier|private
name|PDTextStream
name|stream
decl_stmt|;
comment|/**      * Constructor.      */
specifier|public
name|PDNamedTextStream
parameter_list|()
block|{
comment|//default constructor
block|}
comment|/**      * Constructor.      *      * @param name The name of the stream.      * @param str The stream.      */
specifier|public
name|PDNamedTextStream
parameter_list|(
name|COSName
name|name
parameter_list|,
name|COSBase
name|str
parameter_list|)
block|{
name|streamName
operator|=
name|name
expr_stmt|;
name|stream
operator|=
name|PDTextStream
operator|.
name|createTextStream
argument_list|(
name|str
argument_list|)
expr_stmt|;
block|}
comment|/**      * The name of the named text stream.      *      * @return The stream name.      */
specifier|public
name|String
name|getName
parameter_list|()
block|{
name|String
name|name
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|streamName
operator|!=
literal|null
condition|)
block|{
name|name
operator|=
name|streamName
operator|.
name|getName
argument_list|()
expr_stmt|;
block|}
return|return
name|name
return|;
block|}
comment|/**      * This will set the name of the named text stream.      *      * @param name The name of the named text stream.      */
specifier|public
name|void
name|setName
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|streamName
operator|=
name|COSName
operator|.
name|getPDFName
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the stream.      *      * @return The stream associated with this name.      */
specifier|public
name|PDTextStream
name|getStream
parameter_list|()
block|{
return|return
name|stream
return|;
block|}
comment|/**      * This will set the stream.      *      * @param str The stream associated with this name.      */
specifier|public
name|void
name|setStream
parameter_list|(
name|PDTextStream
name|str
parameter_list|)
block|{
name|stream
operator|=
name|str
expr_stmt|;
block|}
comment|/**      * Convert this standard java object to a COS object.      *      * @return The cos object that matches this Java object.      */
specifier|public
name|COSBase
name|getFirstCOSObject
parameter_list|()
block|{
return|return
name|streamName
return|;
block|}
comment|/**      * Convert this standard java object to a COS object.      *      * @return The cos object that matches this Java object.      */
specifier|public
name|COSBase
name|getSecondCOSObject
parameter_list|()
block|{
name|COSBase
name|retval
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|stream
operator|!=
literal|null
condition|)
block|{
name|retval
operator|=
name|stream
operator|.
name|getCOSObject
argument_list|()
expr_stmt|;
block|}
return|return
name|retval
return|;
block|}
block|}
end_class

end_unit

