begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|tools
operator|.
name|pdfdebugger
operator|.
name|streampane
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|BorderLayout
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Dimension
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|FlowLayout
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|event
operator|.
name|ActionListener
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|BufferedImage
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|BoxLayout
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JComboBox
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|JPanel
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|swing
operator|.
name|text
operator|.
name|StyledDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|tools
operator|.
name|pdfdebugger
operator|.
name|streampane
operator|.
name|tooltip
operator|.
name|ToolTipController
import|;
end_import

begin_comment
comment|/**  * @author Khyrul Bashar  */
end_comment

begin_class
class|class
name|StreamPaneView
extends|extends
name|JPanel
block|{
specifier|private
specifier|final
name|JPanel
name|headerPanel
decl_stmt|;
specifier|private
specifier|final
name|JPanel
name|contentPanel
decl_stmt|;
comment|/**      * Constructor.      * @param filterTypes String array that provides a list of key for available stream versions.      * @param initialChoice String instance. Initial choice for showing in the pane.      * @param listener ActionListener that listens for stream version choice changing.      */
name|StreamPaneView
parameter_list|(
name|String
index|[]
name|filterTypes
parameter_list|,
name|String
name|initialChoice
parameter_list|,
name|ActionListener
name|listener
parameter_list|)
block|{
name|headerPanel
operator|=
name|createHeaderPanel
argument_list|(
name|filterTypes
argument_list|,
name|initialChoice
argument_list|,
name|listener
argument_list|)
expr_stmt|;
name|contentPanel
operator|=
operator|new
name|JPanel
argument_list|(
operator|new
name|BorderLayout
argument_list|()
argument_list|)
expr_stmt|;
name|initUI
argument_list|()
expr_stmt|;
block|}
comment|/**      * This shows the stream in text for any of  it's filtered or unfiltered version.      * @param document StyledDocument instance that holds the text.      * @param toolTipController ToolTipController instance.      */
name|void
name|showStreamText
parameter_list|(
name|StyledDocument
name|document
parameter_list|,
name|ToolTipController
name|toolTipController
parameter_list|)
block|{
name|contentPanel
operator|.
name|removeAll
argument_list|()
expr_stmt|;
name|StreamTextView
name|textView
init|=
operator|new
name|StreamTextView
argument_list|(
name|document
argument_list|,
name|toolTipController
argument_list|)
decl_stmt|;
name|contentPanel
operator|.
name|add
argument_list|(
name|textView
operator|.
name|getView
argument_list|()
argument_list|,
name|BorderLayout
operator|.
name|CENTER
argument_list|)
expr_stmt|;
name|this
operator|.
name|validate
argument_list|()
expr_stmt|;
block|}
comment|/**      * This shows the stream as image.      * @param image BufferedImage instance that holds the text.      */
name|void
name|showStreamImage
parameter_list|(
name|BufferedImage
name|image
parameter_list|)
block|{
name|contentPanel
operator|.
name|removeAll
argument_list|()
expr_stmt|;
name|contentPanel
operator|.
name|add
argument_list|(
operator|new
name|StreamImageView
argument_list|(
name|image
argument_list|)
operator|.
name|getView
argument_list|()
argument_list|,
name|BorderLayout
operator|.
name|CENTER
argument_list|)
expr_stmt|;
name|this
operator|.
name|validate
argument_list|()
expr_stmt|;
block|}
specifier|private
name|JPanel
name|createHeaderPanel
parameter_list|(
name|String
index|[]
name|availableFilters
parameter_list|,
name|String
name|i
parameter_list|,
name|ActionListener
name|actionListener
parameter_list|)
block|{
name|JComboBox
name|filters
init|=
operator|new
name|JComboBox
argument_list|(
name|availableFilters
argument_list|)
decl_stmt|;
name|filters
operator|.
name|setSelectedItem
argument_list|(
name|i
argument_list|)
expr_stmt|;
name|filters
operator|.
name|addActionListener
argument_list|(
name|actionListener
argument_list|)
expr_stmt|;
name|JPanel
name|panel
init|=
operator|new
name|JPanel
argument_list|(
operator|new
name|FlowLayout
argument_list|()
argument_list|)
decl_stmt|;
name|panel
operator|.
name|add
argument_list|(
name|filters
argument_list|)
expr_stmt|;
return|return
name|panel
return|;
block|}
specifier|public
name|JPanel
name|getStreamPanel
parameter_list|()
block|{
return|return
name|this
return|;
block|}
specifier|private
name|void
name|initUI
parameter_list|()
block|{
name|this
operator|.
name|setPreferredSize
argument_list|(
operator|new
name|Dimension
argument_list|(
literal|300
argument_list|,
literal|500
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|setLayout
argument_list|(
operator|new
name|BoxLayout
argument_list|(
name|this
argument_list|,
name|BoxLayout
operator|.
name|Y_AXIS
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|add
argument_list|(
name|headerPanel
argument_list|)
expr_stmt|;
name|this
operator|.
name|add
argument_list|(
name|contentPanel
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

