begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|encryption
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|security
operator|.
name|NoSuchAlgorithmException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|security
operator|.
name|cert
operator|.
name|CertificateFactory
import|;
end_import

begin_import
import|import
name|java
operator|.
name|security
operator|.
name|cert
operator|.
name|X509Certificate
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|crypto
operator|.
name|Cipher
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|io
operator|.
name|MemoryUsageSetting
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|encryption
operator|.
name|AccessPermission
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|encryption
operator|.
name|PublicKeyProtectionPolicy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|encryption
operator|.
name|PublicKeyRecipient
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|text
operator|.
name|PDFTextStripper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|After
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Assert
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|fail
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|runner
operator|.
name|RunWith
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|runners
operator|.
name|Parameterized
import|;
end_import

begin_comment
comment|/**  * Tests for public key encryption. These tests are not perfect - to be sure, encrypt a file by  * using a certificate exported from your digital id in Adobe Reader, and then open that file with  * Adobe Reader. Do this with every key length.  *  * @author Ben Litchfield  */
end_comment

begin_class
annotation|@
name|RunWith
argument_list|(
name|Parameterized
operator|.
name|class
argument_list|)
specifier|public
class|class
name|TestPublicKeyEncryption
block|{
specifier|private
specifier|final
name|File
name|testResultsDir
init|=
operator|new
name|File
argument_list|(
literal|"target/test-output/crypto"
argument_list|)
decl_stmt|;
specifier|private
name|AccessPermission
name|permission1
decl_stmt|;
specifier|private
name|AccessPermission
name|permission2
decl_stmt|;
specifier|private
name|PublicKeyRecipient
name|recipient1
decl_stmt|;
specifier|private
name|PublicKeyRecipient
name|recipient2
decl_stmt|;
specifier|private
name|String
name|keyStore1
decl_stmt|;
specifier|private
name|String
name|keyStore2
decl_stmt|;
specifier|private
name|String
name|password1
decl_stmt|;
specifier|private
name|String
name|password2
decl_stmt|;
comment|/**      * Simple test document that gets encrypted by the test cases.      */
specifier|private
name|PDDocument
name|document
decl_stmt|;
specifier|private
name|String
name|text
decl_stmt|;
specifier|private
name|String
name|producer
decl_stmt|;
annotation|@
name|Parameterized
operator|.
name|Parameter
specifier|public
name|int
name|keyLength
decl_stmt|;
comment|/**      * Values for keyLength test parameter.      *      * @return      */
annotation|@
name|Parameterized
operator|.
name|Parameters
specifier|public
specifier|static
name|Collection
name|keyLengths
parameter_list|()
block|{
return|return
name|Arrays
operator|.
name|asList
argument_list|(
literal|40
argument_list|,
literal|128
argument_list|,
literal|256
argument_list|)
return|;
block|}
specifier|public
name|TestPublicKeyEncryption
parameter_list|()
block|{
name|testResultsDir
operator|.
name|mkdirs
argument_list|()
expr_stmt|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|Before
specifier|public
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
if|if
condition|(
name|Cipher
operator|.
name|getMaxAllowedKeyLength
argument_list|(
literal|"AES"
argument_list|)
operator|!=
name|Integer
operator|.
name|MAX_VALUE
condition|)
block|{
comment|// we need strong encryption for these tests
name|fail
argument_list|(
literal|"JCE unlimited strength jurisdiction policy files are not installed"
argument_list|)
expr_stmt|;
block|}
name|permission1
operator|=
operator|new
name|AccessPermission
argument_list|()
expr_stmt|;
name|permission1
operator|.
name|setCanAssembleDocument
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanExtractContent
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanExtractForAccessibility
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanFillInForm
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanModify
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanModifyAnnotations
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanPrint
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission1
operator|.
name|setCanPrintDegraded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|=
operator|new
name|AccessPermission
argument_list|()
expr_stmt|;
name|permission2
operator|.
name|setCanAssembleDocument
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanExtractContent
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanExtractForAccessibility
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanFillInForm
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanModify
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanModifyAnnotations
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|permission2
operator|.
name|setCanPrint
argument_list|(
literal|true
argument_list|)
expr_stmt|;
comment|// it is true now !
name|permission2
operator|.
name|setCanPrintDegraded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|recipient1
operator|=
name|getRecipient
argument_list|(
literal|"test1.der"
argument_list|,
name|permission1
argument_list|)
expr_stmt|;
name|recipient2
operator|=
name|getRecipient
argument_list|(
literal|"test2.der"
argument_list|,
name|permission2
argument_list|)
expr_stmt|;
name|password1
operator|=
literal|"test1"
expr_stmt|;
name|password2
operator|=
literal|"test2"
expr_stmt|;
name|keyStore1
operator|=
literal|"test1.pfx"
expr_stmt|;
name|keyStore2
operator|=
literal|"test2.pfx"
expr_stmt|;
name|document
operator|=
name|PDDocument
operator|.
name|load
argument_list|(
operator|new
name|File
argument_list|(
name|this
operator|.
name|getClass
argument_list|()
operator|.
name|getResource
argument_list|(
literal|"test.pdf"
argument_list|)
operator|.
name|toURI
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|text
operator|=
operator|new
name|PDFTextStripper
argument_list|()
operator|.
name|getText
argument_list|(
name|document
argument_list|)
expr_stmt|;
name|producer
operator|=
name|document
operator|.
name|getDocumentInformation
argument_list|()
operator|.
name|getProducer
argument_list|()
expr_stmt|;
name|document
operator|.
name|setVersion
argument_list|(
literal|1.7f
argument_list|)
expr_stmt|;
block|}
comment|/**      * {@inheritDoc}      */
annotation|@
name|After
specifier|public
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|document
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
comment|/**      * Protect a document with certificate 1 and try to open it with      * certificate 2 and catch the exception.      *      * @throws Exception If there is an unexpected error during the test.      */
annotation|@
name|Test
specifier|public
name|void
name|testProtectionError
parameter_list|()
throws|throws
name|Exception
block|{
name|PublicKeyProtectionPolicy
name|policy
init|=
operator|new
name|PublicKeyProtectionPolicy
argument_list|()
decl_stmt|;
name|policy
operator|.
name|addRecipient
argument_list|(
name|recipient1
argument_list|)
expr_stmt|;
name|policy
operator|.
name|setEncryptionKeyLength
argument_list|(
name|keyLength
argument_list|)
expr_stmt|;
name|document
operator|.
name|protect
argument_list|(
name|policy
argument_list|)
expr_stmt|;
name|PDDocument
name|encryptedDoc
init|=
literal|null
decl_stmt|;
try|try
block|{
name|File
name|file
init|=
name|save
argument_list|(
literal|"testProtectionError"
argument_list|)
decl_stmt|;
name|encryptedDoc
operator|=
name|reload
argument_list|(
name|file
argument_list|,
name|password2
argument_list|,
name|getKeyStore
argument_list|(
name|keyStore2
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|encryptedDoc
operator|.
name|isEncrypted
argument_list|()
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"No exception when using an incorrect decryption key"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|IOException
name|ex
parameter_list|)
block|{
name|String
name|msg
init|=
name|ex
operator|.
name|getMessage
argument_list|()
decl_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
literal|"not the expected exception: "
operator|+
name|msg
argument_list|,
name|msg
operator|.
name|contains
argument_list|(
literal|"serial-#: rid 2 vs. cert 3"
argument_list|)
argument_list|)
expr_stmt|;
block|}
finally|finally
block|{
if|if
condition|(
name|encryptedDoc
operator|!=
literal|null
condition|)
block|{
name|encryptedDoc
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
block|}
block|}
comment|/**      * Protect a document with a public certificate and try to open it      * with the corresponding private certificate.      *      * @throws Exception If there is an unexpected error during the test.      */
annotation|@
name|Test
specifier|public
name|void
name|testProtection
parameter_list|()
throws|throws
name|Exception
block|{
name|PublicKeyProtectionPolicy
name|policy
init|=
operator|new
name|PublicKeyProtectionPolicy
argument_list|()
decl_stmt|;
name|policy
operator|.
name|addRecipient
argument_list|(
name|recipient1
argument_list|)
expr_stmt|;
name|policy
operator|.
name|setEncryptionKeyLength
argument_list|(
name|keyLength
argument_list|)
expr_stmt|;
name|document
operator|.
name|protect
argument_list|(
name|policy
argument_list|)
expr_stmt|;
name|File
name|file
init|=
name|save
argument_list|(
literal|"testProtection"
argument_list|)
decl_stmt|;
try|try
init|(
name|PDDocument
name|encryptedDoc
init|=
name|reload
argument_list|(
name|file
argument_list|,
name|password1
argument_list|,
name|getKeyStore
argument_list|(
name|keyStore1
argument_list|)
argument_list|)
init|)
block|{
name|Assert
operator|.
name|assertTrue
argument_list|(
name|encryptedDoc
operator|.
name|isEncrypted
argument_list|()
argument_list|)
expr_stmt|;
name|AccessPermission
name|permission
init|=
name|encryptedDoc
operator|.
name|getCurrentAccessPermission
argument_list|()
decl_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canAssembleDocument
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canExtractContent
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|permission
operator|.
name|canExtractForAccessibility
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canFillInForm
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModify
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModifyAnnotations
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canPrint
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canPrintDegraded
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Protect the document for 2 recipients and try to open it.      *      * @throws Exception If there is an error during the test.      */
annotation|@
name|Test
specifier|public
name|void
name|testMultipleRecipients
parameter_list|()
throws|throws
name|Exception
block|{
name|PublicKeyProtectionPolicy
name|policy
init|=
operator|new
name|PublicKeyProtectionPolicy
argument_list|()
decl_stmt|;
name|policy
operator|.
name|addRecipient
argument_list|(
name|recipient1
argument_list|)
expr_stmt|;
name|policy
operator|.
name|addRecipient
argument_list|(
name|recipient2
argument_list|)
expr_stmt|;
name|policy
operator|.
name|setEncryptionKeyLength
argument_list|(
name|keyLength
argument_list|)
expr_stmt|;
name|document
operator|.
name|protect
argument_list|(
name|policy
argument_list|)
expr_stmt|;
comment|// open first time
name|File
name|file
init|=
name|save
argument_list|(
literal|"testMultipleRecipients"
argument_list|)
decl_stmt|;
try|try
init|(
name|PDDocument
name|encryptedDoc1
init|=
name|reload
argument_list|(
name|file
argument_list|,
name|password1
argument_list|,
name|getKeyStore
argument_list|(
name|keyStore1
argument_list|)
argument_list|)
init|)
block|{
name|AccessPermission
name|permission
init|=
name|encryptedDoc1
operator|.
name|getCurrentAccessPermission
argument_list|()
decl_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canAssembleDocument
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canExtractContent
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|permission
operator|.
name|canExtractForAccessibility
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canFillInForm
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModify
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModifyAnnotations
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canPrint
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canPrintDegraded
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|// open second time
try|try
init|(
name|PDDocument
name|encryptedDoc2
init|=
name|reload
argument_list|(
name|file
argument_list|,
name|password2
argument_list|,
name|getKeyStore
argument_list|(
name|keyStore2
argument_list|)
argument_list|)
init|)
block|{
name|AccessPermission
name|permission
init|=
name|encryptedDoc2
operator|.
name|getCurrentAccessPermission
argument_list|()
decl_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canAssembleDocument
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canExtractContent
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|permission
operator|.
name|canExtractForAccessibility
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canFillInForm
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModify
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canModifyAnnotations
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertTrue
argument_list|(
name|permission
operator|.
name|canPrint
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertFalse
argument_list|(
name|permission
operator|.
name|canPrintDegraded
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Reloads the given document from a file and check some contents.      *      * @param file input file      * @param decryptionPassword password to be used to decrypt the doc      * @param keyStore password to be used to decrypt the doc      * @return reloaded document      * @throws Exception if       */
specifier|private
name|PDDocument
name|reload
parameter_list|(
name|File
name|file
parameter_list|,
name|String
name|decryptionPassword
parameter_list|,
name|InputStream
name|keyStore
parameter_list|)
throws|throws
name|IOException
throws|,
name|NoSuchAlgorithmException
block|{
name|PDDocument
name|doc2
init|=
name|PDDocument
operator|.
name|load
argument_list|(
name|file
argument_list|,
name|decryptionPassword
argument_list|,
name|keyStore
argument_list|,
literal|null
argument_list|,
name|MemoryUsageSetting
operator|.
name|setupMainMemoryOnly
argument_list|()
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"Extracted text is different"
argument_list|,
name|text
argument_list|,
operator|new
name|PDFTextStripper
argument_list|()
operator|.
name|getText
argument_list|(
name|doc2
argument_list|)
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
literal|"Producer is different"
argument_list|,
name|producer
argument_list|,
name|doc2
operator|.
name|getDocumentInformation
argument_list|()
operator|.
name|getProducer
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|doc2
return|;
block|}
comment|/**      * Returns a recipient specification with the given access permissions      * and an X.509 certificate read from the given classpath resource.      *      * @param certificate X.509 certificate resource, relative to this class      * @param permission access permissions      * @return recipient specification      * @throws Exception if the certificate could not be read      */
specifier|private
name|PublicKeyRecipient
name|getRecipient
parameter_list|(
name|String
name|certificate
parameter_list|,
name|AccessPermission
name|permission
parameter_list|)
throws|throws
name|Exception
block|{
try|try
init|(
name|InputStream
name|input
init|=
name|TestPublicKeyEncryption
operator|.
name|class
operator|.
name|getResourceAsStream
argument_list|(
name|certificate
argument_list|)
init|)
block|{
name|CertificateFactory
name|factory
init|=
name|CertificateFactory
operator|.
name|getInstance
argument_list|(
literal|"X.509"
argument_list|)
decl_stmt|;
name|PublicKeyRecipient
name|recipient
init|=
operator|new
name|PublicKeyRecipient
argument_list|()
decl_stmt|;
name|recipient
operator|.
name|setPermission
argument_list|(
name|permission
argument_list|)
expr_stmt|;
name|recipient
operator|.
name|setX509
argument_list|(
operator|(
name|X509Certificate
operator|)
name|factory
operator|.
name|generateCertificate
argument_list|(
name|input
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|recipient
return|;
block|}
block|}
specifier|private
name|InputStream
name|getKeyStore
parameter_list|(
name|String
name|name
parameter_list|)
block|{
return|return
name|TestPublicKeyEncryption
operator|.
name|class
operator|.
name|getResourceAsStream
argument_list|(
name|name
argument_list|)
return|;
block|}
specifier|private
name|File
name|save
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|IOException
block|{
name|File
name|file
init|=
operator|new
name|File
argument_list|(
name|testResultsDir
argument_list|,
name|name
operator|+
literal|"-"
operator|+
name|keyLength
operator|+
literal|"bit.pdf"
argument_list|)
decl_stmt|;
name|document
operator|.
name|save
argument_list|(
name|file
argument_list|)
expr_stmt|;
return|return
name|file
return|;
block|}
block|}
end_class

end_unit

