begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*****************************************************************************  *   * Licensed to the Apache Software Foundation (ASF) under one  * or more contributor license agreements.  See the NOTICE file  * distributed with this work for additional information  * regarding copyright ownership.  The ASF licenses this file  * to you under the Apache License, Version 2.0 (the  * "License"); you may not use this file except in compliance  * with the License.  You may obtain a copy of the License at  *   * http://www.apache.org/licenses/LICENSE-2.0  *   * Unless required by applicable law or agreed to in writing,  * software distributed under the License is distributed on an  * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY  * KIND, either express or implied.  See the License for the  * specific language governing permissions and limitations  * under the License.  *   ****************************************************************************/
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|padaf
operator|.
name|xmpbox
operator|.
name|type
package|;
end_package

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|Assert
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|padaf
operator|.
name|xmpbox
operator|.
name|type
operator|.
name|Attribute
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|AttributeTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testAtt
parameter_list|()
block|{
name|String
name|nsUri
init|=
literal|"nsUri"
decl_stmt|;
name|String
name|prefix
init|=
literal|"prefix"
decl_stmt|;
name|String
name|localName
init|=
literal|"localName"
decl_stmt|;
name|String
name|value
init|=
literal|"value"
decl_stmt|;
name|Attribute
name|att
init|=
operator|new
name|Attribute
argument_list|(
name|nsUri
argument_list|,
name|prefix
argument_list|,
name|localName
argument_list|,
name|value
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|nsUri
argument_list|,
name|att
operator|.
name|getNamespace
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|prefix
argument_list|,
name|att
operator|.
name|getPrefix
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName
argument_list|,
name|att
operator|.
name|getLocalName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|prefix
operator|+
literal|":"
operator|+
name|localName
argument_list|,
name|att
operator|.
name|getQualifiedName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|value
argument_list|,
name|att
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
name|String
name|nsUri2
init|=
literal|"nsUri2"
decl_stmt|;
name|String
name|prefix2
init|=
literal|"prefix2"
decl_stmt|;
name|String
name|localName2
init|=
literal|"localName2"
decl_stmt|;
name|String
name|value2
init|=
literal|"value2"
decl_stmt|;
name|att
operator|.
name|setNsURI
argument_list|(
name|nsUri2
argument_list|)
expr_stmt|;
name|att
operator|.
name|setPrefix
argument_list|(
name|prefix2
argument_list|)
expr_stmt|;
name|att
operator|.
name|setLocalName
argument_list|(
name|localName2
argument_list|)
expr_stmt|;
name|att
operator|.
name|setValue
argument_list|(
name|value2
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|nsUri2
argument_list|,
name|att
operator|.
name|getNamespace
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|prefix2
argument_list|,
name|att
operator|.
name|getPrefix
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName2
argument_list|,
name|att
operator|.
name|getLocalName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|prefix2
operator|+
literal|":"
operator|+
name|localName2
argument_list|,
name|att
operator|.
name|getQualifiedName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|value2
argument_list|,
name|att
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testAttWithoutPrefix
parameter_list|()
block|{
name|String
name|nsUri
init|=
literal|"nsUri"
decl_stmt|;
name|String
name|localName
init|=
literal|"localName"
decl_stmt|;
name|String
name|value
init|=
literal|"value"
decl_stmt|;
name|Attribute
name|att
init|=
operator|new
name|Attribute
argument_list|(
name|nsUri
argument_list|,
literal|null
argument_list|,
name|localName
argument_list|,
name|value
argument_list|)
decl_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|nsUri
argument_list|,
name|att
operator|.
name|getNamespace
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertNull
argument_list|(
name|att
operator|.
name|getPrefix
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName
argument_list|,
name|att
operator|.
name|getLocalName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName
argument_list|,
name|att
operator|.
name|getQualifiedName
argument_list|()
argument_list|)
expr_stmt|;
name|att
operator|=
operator|new
name|Attribute
argument_list|(
name|nsUri
argument_list|,
literal|""
argument_list|,
name|localName
argument_list|,
name|value
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|nsUri
argument_list|,
name|att
operator|.
name|getNamespace
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertNull
argument_list|(
name|att
operator|.
name|getPrefix
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName
argument_list|,
name|att
operator|.
name|getLocalName
argument_list|()
argument_list|)
expr_stmt|;
name|Assert
operator|.
name|assertEquals
argument_list|(
name|localName
argument_list|,
name|att
operator|.
name|getQualifiedName
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

