begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Copyright (c) 2004, www.pdfbox.org  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions are met:  *  * 1. Redistributions of source code must retain the above copyright notice,  *    this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright notice,  *    this list of conditions and the following disclaimer in the documentation  *    and/or other materials provided with the distribution.  * 3. Neither the name of pdfbox; nor the names of its  *    contributors may be used to endorse or promote products derived from this  *    software without specific prior written permission.  *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE  * DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY  * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES  * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;  * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON  * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT  * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  *  * http://www.pdfbox.org  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|action
operator|.
name|type
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
operator|.
name|filespecification
operator|.
name|PDFileSpecification
import|;
end_import

begin_comment
comment|/**  * This represents a remote go-to action that can be executed in a PDF document.  *  * @author<a href="mailto:ben@benlitchfield.com">Ben Litchfield</a>  * @author Panagiotis Toumasis (ptoumasis@mail.gr)  * @version $Revision: 1.4 $  */
end_comment

begin_class
specifier|public
class|class
name|PDActionRemoteGoTo
extends|extends
name|PDAction
block|{
comment|/**      * This type of action this object represents.      */
specifier|public
specifier|static
specifier|final
name|String
name|SUB_TYPE
init|=
literal|"GoToR"
decl_stmt|;
comment|/**      * Default constructor.      */
specifier|public
name|PDActionRemoteGoTo
parameter_list|()
block|{
name|action
operator|=
operator|new
name|COSDictionary
argument_list|()
expr_stmt|;
name|setSubType
argument_list|(
name|SUB_TYPE
argument_list|)
expr_stmt|;
block|}
comment|/**      * Constructor.      *      * @param a The action dictionary.      */
specifier|public
name|PDActionRemoteGoTo
parameter_list|(
name|COSDictionary
name|a
parameter_list|)
block|{
name|super
argument_list|(
name|a
argument_list|)
expr_stmt|;
block|}
comment|/**      * Convert this standard java object to a COS object.      *      * @return The cos object that matches this Java object.      */
specifier|public
name|COSBase
name|getCOSObject
parameter_list|()
block|{
return|return
name|action
return|;
block|}
comment|/**      * Convert this standard java object to a COS object.      *      * @return The cos object that matches this Java object.      */
specifier|public
name|COSDictionary
name|getCOSDictionary
parameter_list|()
block|{
return|return
name|action
return|;
block|}
comment|/**      * This will get the type of action that the actions dictionary describes.      * It must be GoToR for a remote go-to action.      *      * @return The S entry of the specific remote go-to action dictionary.      */
specifier|public
name|String
name|getS
parameter_list|()
block|{
return|return
name|action
operator|.
name|getNameAsString
argument_list|(
literal|"S"
argument_list|)
return|;
block|}
comment|/**      * This will set the type of action that the actions dictionary describes.      * It must be GoToR for a remote go-to action.      *      * @param s The remote go-to action.      */
specifier|public
name|void
name|setS
parameter_list|(
name|String
name|s
parameter_list|)
block|{
name|action
operator|.
name|setName
argument_list|(
literal|"S"
argument_list|,
name|s
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the file in which the destination is located.      *      * @return The F entry of the specific remote go-to action dictionary.      *       * @throws IOException If there is an error creating the file spec.      */
specifier|public
name|PDFileSpecification
name|getFile
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|PDFileSpecification
operator|.
name|createFS
argument_list|(
name|action
operator|.
name|getDictionaryObject
argument_list|(
literal|"F"
argument_list|)
argument_list|)
return|;
block|}
comment|/**      * This will set the file in which the destination is located.      *      * @param fs The file specification.      */
specifier|public
name|void
name|setFile
parameter_list|(
name|PDFileSpecification
name|fs
parameter_list|)
block|{
name|action
operator|.
name|setItem
argument_list|(
literal|"F"
argument_list|,
name|fs
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will get the destination to jump to.      * If the value is an array defining an explicit destination,      * its first element must be a page number within the remote      * document rather than an indirect reference to a page object      * in the current document. The first page is numbered 0.      *      * @return The D entry of the specific remote go-to action dictionary.      */
comment|// Array or String.
specifier|public
name|COSBase
name|getD
parameter_list|()
block|{
return|return
name|action
operator|.
name|getDictionaryObject
argument_list|(
literal|"D"
argument_list|)
return|;
block|}
comment|/**      * This will set the destination to jump to.      * If the value is an array defining an explicit destination,      * its first element must be a page number within the remote      * document rather than an indirect reference to a page object      * in the current document. The first page is numbered 0.      *      * @param d The destination.      */
comment|// In case the value is an array.
specifier|public
name|void
name|setD
parameter_list|(
name|COSBase
name|d
parameter_list|)
block|{
name|action
operator|.
name|setItem
argument_list|(
literal|"D"
argument_list|,
name|d
argument_list|)
expr_stmt|;
block|}
comment|/**      * This will specify whether to open the destination document in a new window.      * If this flag is false, the destination document will replace the current      * document in the same window. If this entry is absent, the viewer application      * should behave in accordance with the current user preference.      *      * @return A flag specifying whether to open the destination document in a new window.      */
specifier|public
name|boolean
name|shouldOpenInNewWindow
parameter_list|()
block|{
return|return
name|action
operator|.
name|getBoolean
argument_list|(
literal|"NewWindow"
argument_list|,
literal|true
argument_list|)
return|;
block|}
comment|/**      * This will specify the destination document to open in a new window.      *      * @param value The flag value.      */
specifier|public
name|void
name|setOpenInNewWindow
parameter_list|(
name|boolean
name|value
parameter_list|)
block|{
name|action
operator|.
name|setBoolean
argument_list|(
literal|"NewWindow"
argument_list|,
name|value
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

