begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|rendering
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|BasicStroke
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Color
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Graphics
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Graphics2D
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|GraphicsDevice
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Paint
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|RenderingHints
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Shape
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Stroke
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|TexturePaint
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|AffineTransform
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|Area
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|GeneralPath
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|PathIterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|Point2D
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|geom
operator|.
name|Rectangle2D
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|BufferedImage
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|ColorModel
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|Raster
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|WritableRaster
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|Log
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|logging
operator|.
name|LogFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|contentstream
operator|.
name|PDFGraphicsStreamEngine
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSArray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSBase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSNumber
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
operator|.
name|PDRectangle
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
operator|.
name|function
operator|.
name|PDFunction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDCIDFontType0
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDCIDFontType2
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDFont
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDTrueTypeFont
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDType0Font
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDType1CFont
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|font
operator|.
name|PDType1Font
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|PDLineDashPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|blend
operator|.
name|SoftMaskPaint
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDColor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDColorSpace
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDDeviceGray
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|color
operator|.
name|PDPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|form
operator|.
name|PDTransparencyGroup
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|image
operator|.
name|PDImage
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|pattern
operator|.
name|PDAbstractPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|pattern
operator|.
name|PDShadingPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|pattern
operator|.
name|PDTilingPattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|shading
operator|.
name|PDShading
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|state
operator|.
name|PDGraphicsState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|state
operator|.
name|PDSoftMask
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|state
operator|.
name|RenderingMode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|PDAnnotation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|PDAnnotationLink
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|PDAnnotationMarkup
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|PDBorderStyleDictionary
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|util
operator|.
name|Matrix
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|util
operator|.
name|Vector
import|;
end_import

begin_comment
comment|/**  * Paints a page in a PDF document to a Graphics context. May be subclassed to provide custom  * rendering.  *   *<p>If you want to do custom graphics processing rather than Graphics2D rendering, then you should  * subclass PDFGraphicsStreamEngine instead. Subclassing PageDrawer is only suitable for cases  * where the goal is to render onto a Graphics2D surface.  *   * @author Ben Litchfield  */
end_comment

begin_class
specifier|public
class|class
name|PageDrawer
extends|extends
name|PDFGraphicsStreamEngine
block|{
specifier|private
specifier|static
specifier|final
name|Log
name|LOG
init|=
name|LogFactory
operator|.
name|getLog
argument_list|(
name|PageDrawer
operator|.
name|class
argument_list|)
decl_stmt|;
comment|// parent document renderer - note: this is needed for not-yet-implemented resource caching
specifier|private
specifier|final
name|PDFRenderer
name|renderer
decl_stmt|;
comment|// the graphics device to draw to, xform is the initial transform of the device (i.e. DPI)
specifier|private
name|Graphics2D
name|graphics
decl_stmt|;
specifier|private
name|AffineTransform
name|xform
decl_stmt|;
comment|// the page box to draw (usually the crop box but may be another)
specifier|private
name|PDRectangle
name|pageSize
decl_stmt|;
comment|// clipping winding rule used for the clipping path
specifier|private
name|int
name|clipWindingRule
init|=
operator|-
literal|1
decl_stmt|;
specifier|private
name|GeneralPath
name|linePath
init|=
operator|new
name|GeneralPath
argument_list|()
decl_stmt|;
comment|// last clipping path
specifier|private
name|Area
name|lastClip
decl_stmt|;
comment|// buffered clipping area for text being drawn
specifier|private
name|Area
name|textClippingArea
decl_stmt|;
comment|// glyph cache
specifier|private
specifier|final
name|Map
argument_list|<
name|PDFont
argument_list|,
name|Glyph2D
argument_list|>
name|fontGlyph2D
init|=
operator|new
name|HashMap
argument_list|<
name|PDFont
argument_list|,
name|Glyph2D
argument_list|>
argument_list|()
decl_stmt|;
comment|/**      * Constructor.      *      * @param parameters Parameters for page drawing.      * @throws IOException If there is an error loading properties from the file.      */
specifier|public
name|PageDrawer
parameter_list|(
name|PageDrawerParameters
name|parameters
parameter_list|)
throws|throws
name|IOException
block|{
name|super
argument_list|(
name|parameters
operator|.
name|getPage
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|renderer
operator|=
name|parameters
operator|.
name|getRenderer
argument_list|()
expr_stmt|;
block|}
comment|/**      * Returns the parent renderer.      */
specifier|public
specifier|final
name|PDFRenderer
name|getRenderer
parameter_list|()
block|{
return|return
name|renderer
return|;
block|}
comment|/**      * Returns the underlying Graphics2D. May be null if drawPage has not yet been called.      */
specifier|protected
specifier|final
name|Graphics2D
name|getGraphics
parameter_list|()
block|{
return|return
name|graphics
return|;
block|}
comment|/**      * Returns the current line path. This is reset to empty after each fill/stroke.      */
specifier|protected
specifier|final
name|GeneralPath
name|getLinePath
parameter_list|()
block|{
return|return
name|linePath
return|;
block|}
comment|/**      * Sets high-quality rendering hints on the current Graphics2D.      */
specifier|private
name|void
name|setRenderingHints
parameter_list|()
block|{
name|graphics
operator|.
name|setRenderingHint
argument_list|(
name|RenderingHints
operator|.
name|KEY_INTERPOLATION
argument_list|,
name|RenderingHints
operator|.
name|VALUE_INTERPOLATION_BICUBIC
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setRenderingHint
argument_list|(
name|RenderingHints
operator|.
name|KEY_RENDERING
argument_list|,
name|RenderingHints
operator|.
name|VALUE_RENDER_QUALITY
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setRenderingHint
argument_list|(
name|RenderingHints
operator|.
name|KEY_ANTIALIASING
argument_list|,
name|RenderingHints
operator|.
name|VALUE_ANTIALIAS_ON
argument_list|)
expr_stmt|;
block|}
comment|/**      * Draws the page to the requested context.      *       * @param g The graphics context to draw onto.      * @param pageSize The size of the page to draw.      * @throws IOException If there is an IO error while drawing the page.      */
specifier|public
name|void
name|drawPage
parameter_list|(
name|Graphics
name|g
parameter_list|,
name|PDRectangle
name|pageSize
parameter_list|)
throws|throws
name|IOException
block|{
name|graphics
operator|=
operator|(
name|Graphics2D
operator|)
name|g
expr_stmt|;
name|xform
operator|=
name|graphics
operator|.
name|getTransform
argument_list|()
expr_stmt|;
name|this
operator|.
name|pageSize
operator|=
name|pageSize
expr_stmt|;
name|setRenderingHints
argument_list|()
expr_stmt|;
name|graphics
operator|.
name|translate
argument_list|(
literal|0
argument_list|,
name|pageSize
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|scale
argument_list|(
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|// TODO use getStroke() to set the initial stroke
name|graphics
operator|.
name|setStroke
argument_list|(
operator|new
name|BasicStroke
argument_list|(
literal|1.0f
argument_list|,
name|BasicStroke
operator|.
name|CAP_BUTT
argument_list|,
name|BasicStroke
operator|.
name|JOIN_MITER
argument_list|)
argument_list|)
expr_stmt|;
comment|// adjust for non-(0,0) crop box
name|graphics
operator|.
name|translate
argument_list|(
operator|-
name|pageSize
operator|.
name|getLowerLeftX
argument_list|()
argument_list|,
operator|-
name|pageSize
operator|.
name|getLowerLeftY
argument_list|()
argument_list|)
expr_stmt|;
name|processPage
argument_list|(
name|getPage
argument_list|()
argument_list|)
expr_stmt|;
for|for
control|(
name|PDAnnotation
name|annotation
range|:
name|getPage
argument_list|()
operator|.
name|getAnnotations
argument_list|()
control|)
block|{
name|showAnnotation
argument_list|(
name|annotation
argument_list|)
expr_stmt|;
block|}
name|graphics
operator|=
literal|null
expr_stmt|;
block|}
comment|/**      * Draws the pattern stream to the requested context.      *      * @param g The graphics context to draw onto.      * @param pattern The tiling pattern to be used.      * @param colorSpace color space for this tiling.      * @param color color for this tiling.      * @param patternMatrix the pattern matrix      * @throws IOException If there is an IO error while drawing the page.      */
name|void
name|drawTilingPattern
parameter_list|(
name|Graphics2D
name|g
parameter_list|,
name|PDTilingPattern
name|pattern
parameter_list|,
name|PDColorSpace
name|colorSpace
parameter_list|,
name|PDColor
name|color
parameter_list|,
name|Matrix
name|patternMatrix
parameter_list|)
throws|throws
name|IOException
block|{
name|Graphics2D
name|oldGraphics
init|=
name|graphics
decl_stmt|;
name|graphics
operator|=
name|g
expr_stmt|;
name|GeneralPath
name|oldLinePath
init|=
name|linePath
decl_stmt|;
name|linePath
operator|=
operator|new
name|GeneralPath
argument_list|()
expr_stmt|;
name|Area
name|oldLastClip
init|=
name|lastClip
decl_stmt|;
name|lastClip
operator|=
literal|null
expr_stmt|;
name|setRenderingHints
argument_list|()
expr_stmt|;
name|processTilingPattern
argument_list|(
name|pattern
argument_list|,
name|color
argument_list|,
name|colorSpace
argument_list|,
name|patternMatrix
argument_list|)
expr_stmt|;
name|graphics
operator|=
name|oldGraphics
expr_stmt|;
name|linePath
operator|=
name|oldLinePath
expr_stmt|;
name|lastClip
operator|=
name|oldLastClip
expr_stmt|;
block|}
comment|/**      * Returns an AWT paint for the given PDColor.      */
specifier|protected
name|Paint
name|getPaint
parameter_list|(
name|PDColor
name|color
parameter_list|)
throws|throws
name|IOException
block|{
name|PDColorSpace
name|colorSpace
init|=
name|color
operator|.
name|getColorSpace
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
operator|(
name|colorSpace
operator|instanceof
name|PDPattern
operator|)
condition|)
block|{
name|float
index|[]
name|rgb
init|=
name|colorSpace
operator|.
name|toRGB
argument_list|(
name|color
operator|.
name|getComponents
argument_list|()
argument_list|)
decl_stmt|;
return|return
operator|new
name|Color
argument_list|(
name|rgb
index|[
literal|0
index|]
argument_list|,
name|rgb
index|[
literal|1
index|]
argument_list|,
name|rgb
index|[
literal|2
index|]
argument_list|)
return|;
block|}
else|else
block|{
name|PDPattern
name|patternSpace
init|=
operator|(
name|PDPattern
operator|)
name|colorSpace
decl_stmt|;
name|PDAbstractPattern
name|pattern
init|=
name|patternSpace
operator|.
name|getPattern
argument_list|(
name|color
argument_list|)
decl_stmt|;
if|if
condition|(
name|pattern
operator|instanceof
name|PDTilingPattern
condition|)
block|{
name|PDTilingPattern
name|tilingPattern
init|=
operator|(
name|PDTilingPattern
operator|)
name|pattern
decl_stmt|;
if|if
condition|(
name|tilingPattern
operator|.
name|getPaintType
argument_list|()
operator|==
name|PDTilingPattern
operator|.
name|PAINT_COLORED
condition|)
block|{
comment|// colored tiling pattern
return|return
operator|new
name|TilingPaint
argument_list|(
name|this
argument_list|,
name|tilingPattern
argument_list|,
name|xform
argument_list|)
return|;
block|}
else|else
block|{
comment|// uncolored tiling pattern
return|return
operator|new
name|TilingPaint
argument_list|(
name|this
argument_list|,
name|tilingPattern
argument_list|,
name|patternSpace
operator|.
name|getUnderlyingColorSpace
argument_list|()
argument_list|,
name|color
argument_list|,
name|xform
argument_list|)
return|;
block|}
block|}
else|else
block|{
name|PDShadingPattern
name|shadingPattern
init|=
operator|(
name|PDShadingPattern
operator|)
name|pattern
decl_stmt|;
name|PDShading
name|shading
init|=
name|shadingPattern
operator|.
name|getShading
argument_list|()
decl_stmt|;
if|if
condition|(
name|shading
operator|==
literal|null
condition|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"shadingPattern is null, will be filled with transparency"
argument_list|)
expr_stmt|;
return|return
operator|new
name|Color
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
return|;
block|}
return|return
name|shading
operator|.
name|toPaint
argument_list|(
name|Matrix
operator|.
name|concatenate
argument_list|(
name|getInitialMatrix
argument_list|()
argument_list|,
name|shadingPattern
operator|.
name|getMatrix
argument_list|()
argument_list|)
argument_list|)
return|;
block|}
block|}
block|}
comment|// sets the clipping path using caching for performance, we track lastClip manually because
comment|// Graphics2D#getClip() returns a new object instead of the same one passed to setClip
specifier|private
name|void
name|setClip
parameter_list|()
block|{
name|Area
name|clippingPath
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentClippingPath
argument_list|()
decl_stmt|;
if|if
condition|(
name|clippingPath
operator|!=
name|lastClip
condition|)
block|{
name|graphics
operator|.
name|setClip
argument_list|(
name|clippingPath
argument_list|)
expr_stmt|;
name|lastClip
operator|=
name|clippingPath
expr_stmt|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|void
name|beginText
parameter_list|()
throws|throws
name|IOException
block|{
name|setClip
argument_list|()
expr_stmt|;
name|beginTextClip
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|endText
parameter_list|()
throws|throws
name|IOException
block|{
name|endTextClip
argument_list|()
expr_stmt|;
block|}
comment|/**      * Begin buffering the text clipping path, if any.      */
specifier|private
name|void
name|beginTextClip
parameter_list|()
block|{
comment|// buffer the text clip because it represents a single clipping area
name|textClippingArea
operator|=
operator|new
name|Area
argument_list|()
expr_stmt|;
block|}
comment|/**      * End buffering the text clipping path, if any.      */
specifier|private
name|void
name|endTextClip
parameter_list|()
block|{
name|PDGraphicsState
name|state
init|=
name|getGraphicsState
argument_list|()
decl_stmt|;
name|RenderingMode
name|renderingMode
init|=
name|state
operator|.
name|getTextState
argument_list|()
operator|.
name|getRenderingMode
argument_list|()
decl_stmt|;
comment|// apply the buffered clip as one area
if|if
condition|(
name|renderingMode
operator|.
name|isClip
argument_list|()
operator|&&
operator|!
name|textClippingArea
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|state
operator|.
name|intersectClippingPath
argument_list|(
name|textClippingArea
argument_list|)
expr_stmt|;
name|textClippingArea
operator|=
literal|null
expr_stmt|;
block|}
block|}
annotation|@
name|Override
specifier|protected
name|void
name|showFontGlyph
parameter_list|(
name|Matrix
name|textRenderingMatrix
parameter_list|,
name|PDFont
name|font
parameter_list|,
name|int
name|code
parameter_list|,
name|String
name|unicode
parameter_list|,
name|Vector
name|displacement
parameter_list|)
throws|throws
name|IOException
block|{
name|AffineTransform
name|at
init|=
name|textRenderingMatrix
operator|.
name|createAffineTransform
argument_list|()
decl_stmt|;
name|at
operator|.
name|concatenate
argument_list|(
name|font
operator|.
name|getFontMatrix
argument_list|()
operator|.
name|createAffineTransform
argument_list|()
argument_list|)
expr_stmt|;
name|Glyph2D
name|glyph2D
init|=
name|createGlyph2D
argument_list|(
name|font
argument_list|)
decl_stmt|;
name|drawGlyph2D
argument_list|(
name|glyph2D
argument_list|,
name|font
argument_list|,
name|code
argument_list|,
name|displacement
argument_list|,
name|at
argument_list|)
expr_stmt|;
block|}
comment|/**      * Render the font using the Glyph2D interface.      *       * @param glyph2D the Glyph2D implementation provided a GeneralPath for each glyph      * @param font the font      * @param code character code      * @param displacement the glyph's displacement (advance)      * @param at the transformation      * @throws IOException if something went wrong      */
specifier|private
name|void
name|drawGlyph2D
parameter_list|(
name|Glyph2D
name|glyph2D
parameter_list|,
name|PDFont
name|font
parameter_list|,
name|int
name|code
parameter_list|,
name|Vector
name|displacement
parameter_list|,
name|AffineTransform
name|at
parameter_list|)
throws|throws
name|IOException
block|{
name|PDGraphicsState
name|state
init|=
name|getGraphicsState
argument_list|()
decl_stmt|;
name|RenderingMode
name|renderingMode
init|=
name|state
operator|.
name|getTextState
argument_list|()
operator|.
name|getRenderingMode
argument_list|()
decl_stmt|;
name|GeneralPath
name|path
init|=
name|glyph2D
operator|.
name|getPathForCharacterCode
argument_list|(
name|code
argument_list|)
decl_stmt|;
if|if
condition|(
name|path
operator|!=
literal|null
condition|)
block|{
comment|// stretch non-embedded glyph if it does not match the width contained in the PDF
if|if
condition|(
operator|!
name|font
operator|.
name|isEmbedded
argument_list|()
condition|)
block|{
name|float
name|fontWidth
init|=
name|font
operator|.
name|getWidthFromFont
argument_list|(
name|code
argument_list|)
decl_stmt|;
if|if
condition|(
name|fontWidth
operator|>
literal|0
operator|&&
comment|// ignore spaces
name|Math
operator|.
name|abs
argument_list|(
name|fontWidth
operator|-
name|displacement
operator|.
name|getX
argument_list|()
operator|*
literal|1000
argument_list|)
operator|>
literal|0.0001
condition|)
block|{
name|float
name|pdfWidth
init|=
name|displacement
operator|.
name|getX
argument_list|()
operator|*
literal|1000
decl_stmt|;
name|at
operator|.
name|scale
argument_list|(
name|pdfWidth
operator|/
name|fontWidth
argument_list|,
literal|1
argument_list|)
expr_stmt|;
block|}
block|}
comment|// render glyph
name|Shape
name|glyph
init|=
name|at
operator|.
name|createTransformedShape
argument_list|(
name|path
argument_list|)
decl_stmt|;
if|if
condition|(
name|renderingMode
operator|.
name|isFill
argument_list|()
condition|)
block|{
name|graphics
operator|.
name|setComposite
argument_list|(
name|state
operator|.
name|getNonStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|getNonStrokingPaint
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
name|graphics
operator|.
name|fill
argument_list|(
name|glyph
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|renderingMode
operator|.
name|isStroke
argument_list|()
condition|)
block|{
name|graphics
operator|.
name|setComposite
argument_list|(
name|state
operator|.
name|getStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|getStrokingPaint
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setStroke
argument_list|(
name|getStroke
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
name|graphics
operator|.
name|draw
argument_list|(
name|glyph
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|renderingMode
operator|.
name|isClip
argument_list|()
condition|)
block|{
name|textClippingArea
operator|.
name|add
argument_list|(
operator|new
name|Area
argument_list|(
name|glyph
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
block|}
comment|/**      * Provide a Glyph2D for the given font.      *       * @param font the font      * @return the implementation of the Glyph2D interface for the given font      * @throws IOException if something went wrong      */
specifier|private
name|Glyph2D
name|createGlyph2D
parameter_list|(
name|PDFont
name|font
parameter_list|)
throws|throws
name|IOException
block|{
name|Glyph2D
name|glyph2D
init|=
name|fontGlyph2D
operator|.
name|get
argument_list|(
name|font
argument_list|)
decl_stmt|;
comment|// Is there already a Glyph2D for the given font?
if|if
condition|(
name|glyph2D
operator|!=
literal|null
condition|)
block|{
return|return
name|glyph2D
return|;
block|}
if|if
condition|(
name|font
operator|instanceof
name|PDTrueTypeFont
condition|)
block|{
name|PDTrueTypeFont
name|ttfFont
init|=
operator|(
name|PDTrueTypeFont
operator|)
name|font
decl_stmt|;
name|glyph2D
operator|=
operator|new
name|TTFGlyph2D
argument_list|(
name|ttfFont
argument_list|)
expr_stmt|;
comment|// TTF is never null
block|}
elseif|else
if|if
condition|(
name|font
operator|instanceof
name|PDType1Font
condition|)
block|{
name|PDType1Font
name|pdType1Font
init|=
operator|(
name|PDType1Font
operator|)
name|font
decl_stmt|;
name|glyph2D
operator|=
operator|new
name|Type1Glyph2D
argument_list|(
name|pdType1Font
argument_list|)
expr_stmt|;
comment|// T1 is never null
block|}
elseif|else
if|if
condition|(
name|font
operator|instanceof
name|PDType1CFont
condition|)
block|{
name|PDType1CFont
name|type1CFont
init|=
operator|(
name|PDType1CFont
operator|)
name|font
decl_stmt|;
name|glyph2D
operator|=
operator|new
name|Type1Glyph2D
argument_list|(
name|type1CFont
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|font
operator|instanceof
name|PDType0Font
condition|)
block|{
name|PDType0Font
name|type0Font
init|=
operator|(
name|PDType0Font
operator|)
name|font
decl_stmt|;
if|if
condition|(
name|type0Font
operator|.
name|getDescendantFont
argument_list|()
operator|instanceof
name|PDCIDFontType2
condition|)
block|{
name|glyph2D
operator|=
operator|new
name|TTFGlyph2D
argument_list|(
name|type0Font
argument_list|)
expr_stmt|;
comment|// TTF is never null
block|}
elseif|else
if|if
condition|(
name|type0Font
operator|.
name|getDescendantFont
argument_list|()
operator|instanceof
name|PDCIDFontType0
condition|)
block|{
comment|// a Type0 CIDFont contains CFF font
name|PDCIDFontType0
name|cidType0Font
init|=
operator|(
name|PDCIDFontType0
operator|)
name|type0Font
operator|.
name|getDescendantFont
argument_list|()
decl_stmt|;
name|glyph2D
operator|=
operator|new
name|CIDType0Glyph2D
argument_list|(
name|cidType0Font
argument_list|)
expr_stmt|;
comment|// todo: could be null (need incorporate fallback)
block|}
block|}
else|else
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"Bad font type: "
operator|+
name|font
operator|.
name|getClass
argument_list|()
operator|.
name|getSimpleName
argument_list|()
argument_list|)
throw|;
block|}
comment|// cache the Glyph2D instance
if|if
condition|(
name|glyph2D
operator|!=
literal|null
condition|)
block|{
name|fontGlyph2D
operator|.
name|put
argument_list|(
name|font
argument_list|,
name|glyph2D
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|glyph2D
operator|==
literal|null
condition|)
block|{
comment|// todo: make sure this never happens
throw|throw
operator|new
name|UnsupportedOperationException
argument_list|(
literal|"No font for "
operator|+
name|font
operator|.
name|getName
argument_list|()
argument_list|)
throw|;
block|}
return|return
name|glyph2D
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|appendRectangle
parameter_list|(
name|Point2D
name|p0
parameter_list|,
name|Point2D
name|p1
parameter_list|,
name|Point2D
name|p2
parameter_list|,
name|Point2D
name|p3
parameter_list|)
block|{
comment|// to ensure that the path is created in the right direction, we have to create
comment|// it by combining single lines instead of creating a simple rectangle
name|linePath
operator|.
name|moveTo
argument_list|(
operator|(
name|float
operator|)
name|p0
operator|.
name|getX
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|p0
operator|.
name|getY
argument_list|()
argument_list|)
expr_stmt|;
name|linePath
operator|.
name|lineTo
argument_list|(
operator|(
name|float
operator|)
name|p1
operator|.
name|getX
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|p1
operator|.
name|getY
argument_list|()
argument_list|)
expr_stmt|;
name|linePath
operator|.
name|lineTo
argument_list|(
operator|(
name|float
operator|)
name|p2
operator|.
name|getX
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|p2
operator|.
name|getY
argument_list|()
argument_list|)
expr_stmt|;
name|linePath
operator|.
name|lineTo
argument_list|(
operator|(
name|float
operator|)
name|p3
operator|.
name|getX
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|p3
operator|.
name|getY
argument_list|()
argument_list|)
expr_stmt|;
comment|// close the subpath instead of adding the last line so that a possible set line
comment|// cap style isn't taken into account at the "beginning" of the rectangle
name|linePath
operator|.
name|closePath
argument_list|()
expr_stmt|;
block|}
comment|/**      * Generates AWT raster for a soft mask      *       * @param softMask soft mask      * @return AWT raster for soft mask      * @throws IOException      */
specifier|private
name|Raster
name|createSoftMaskRaster
parameter_list|(
name|PDSoftMask
name|softMask
parameter_list|)
throws|throws
name|IOException
block|{
name|TransparencyGroup
name|transparencyGroup
init|=
operator|new
name|TransparencyGroup
argument_list|(
name|softMask
operator|.
name|getGroup
argument_list|()
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|COSName
name|subtype
init|=
name|softMask
operator|.
name|getSubType
argument_list|()
decl_stmt|;
if|if
condition|(
name|COSName
operator|.
name|ALPHA
operator|.
name|equals
argument_list|(
name|subtype
argument_list|)
condition|)
block|{
return|return
name|transparencyGroup
operator|.
name|getAlphaRaster
argument_list|()
return|;
block|}
elseif|else
if|if
condition|(
name|COSName
operator|.
name|LUMINOSITY
operator|.
name|equals
argument_list|(
name|subtype
argument_list|)
condition|)
block|{
return|return
name|transparencyGroup
operator|.
name|getLuminosityRaster
argument_list|()
return|;
block|}
else|else
block|{
throw|throw
operator|new
name|IOException
argument_list|(
literal|"Invalid soft mask subtype."
argument_list|)
throw|;
block|}
block|}
specifier|private
name|Paint
name|applySoftMaskToPaint
parameter_list|(
name|Paint
name|parentPaint
parameter_list|,
name|PDSoftMask
name|softMask
parameter_list|)
throws|throws
name|IOException
block|{
if|if
condition|(
name|softMask
operator|!=
literal|null
condition|)
block|{
comment|//TODO PDFBOX-2934
if|if
condition|(
name|COSName
operator|.
name|ALPHA
operator|.
name|equals
argument_list|(
name|softMask
operator|.
name|getSubType
argument_list|()
argument_list|)
condition|)
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"alpha smask not implemented yet, is ignored"
argument_list|)
expr_stmt|;
return|return
name|parentPaint
return|;
block|}
return|return
operator|new
name|SoftMaskPaint
argument_list|(
name|parentPaint
argument_list|,
name|createSoftMaskRaster
argument_list|(
name|softMask
argument_list|)
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|parentPaint
return|;
block|}
block|}
comment|// returns the stroking AWT Paint
specifier|private
name|Paint
name|getStrokingPaint
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|applySoftMaskToPaint
argument_list|(
name|getPaint
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getStrokingColor
argument_list|()
argument_list|)
argument_list|,
name|getGraphicsState
argument_list|()
operator|.
name|getSoftMask
argument_list|()
argument_list|)
return|;
block|}
comment|// returns the non-stroking AWT Paint
specifier|private
name|Paint
name|getNonStrokingPaint
parameter_list|()
throws|throws
name|IOException
block|{
return|return
name|getPaint
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getNonStrokingColor
argument_list|()
argument_list|)
return|;
block|}
comment|// create a new stroke based on the current CTM and the current stroke
specifier|private
name|BasicStroke
name|getStroke
parameter_list|()
block|{
name|PDGraphicsState
name|state
init|=
name|getGraphicsState
argument_list|()
decl_stmt|;
comment|// apply the CTM
name|float
name|lineWidth
init|=
name|transformWidth
argument_list|(
name|state
operator|.
name|getLineWidth
argument_list|()
argument_list|)
decl_stmt|;
comment|// minimum line width as used by Adobe Reader
if|if
condition|(
name|lineWidth
operator|<
literal|0.25
condition|)
block|{
name|lineWidth
operator|=
literal|0.25f
expr_stmt|;
block|}
name|PDLineDashPattern
name|dashPattern
init|=
name|state
operator|.
name|getLineDashPattern
argument_list|()
decl_stmt|;
name|int
name|phaseStart
init|=
name|dashPattern
operator|.
name|getPhase
argument_list|()
decl_stmt|;
name|float
index|[]
name|dashArray
init|=
name|dashPattern
operator|.
name|getDashArray
argument_list|()
decl_stmt|;
if|if
condition|(
name|dashArray
operator|!=
literal|null
condition|)
block|{
comment|// apply the CTM
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|dashArray
operator|.
name|length
condition|;
operator|++
name|i
control|)
block|{
comment|// minimum line dash width avoids JVM crash, see PDFBOX-2373, PDFBOX-2929, PDFBOX-3204
name|float
name|w
init|=
name|transformWidth
argument_list|(
name|dashArray
index|[
name|i
index|]
argument_list|)
decl_stmt|;
if|if
condition|(
name|w
operator|!=
literal|0
condition|)
block|{
name|dashArray
index|[
name|i
index|]
operator|=
name|Math
operator|.
name|max
argument_list|(
name|w
argument_list|,
literal|0.035f
argument_list|)
expr_stmt|;
block|}
block|}
name|phaseStart
operator|=
operator|(
name|int
operator|)
name|transformWidth
argument_list|(
name|phaseStart
argument_list|)
expr_stmt|;
comment|// empty dash array is illegal
if|if
condition|(
name|dashArray
operator|.
name|length
operator|==
literal|0
condition|)
block|{
name|dashArray
operator|=
literal|null
expr_stmt|;
block|}
block|}
return|return
operator|new
name|BasicStroke
argument_list|(
name|lineWidth
argument_list|,
name|state
operator|.
name|getLineCap
argument_list|()
argument_list|,
name|state
operator|.
name|getLineJoin
argument_list|()
argument_list|,
name|state
operator|.
name|getMiterLimit
argument_list|()
argument_list|,
name|dashArray
argument_list|,
name|phaseStart
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|strokePath
parameter_list|()
throws|throws
name|IOException
block|{
name|graphics
operator|.
name|setComposite
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|getStrokingPaint
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setStroke
argument_list|(
name|getStroke
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
name|graphics
operator|.
name|draw
argument_list|(
name|linePath
argument_list|)
expr_stmt|;
name|linePath
operator|.
name|reset
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|fillPath
parameter_list|(
name|int
name|windingRule
parameter_list|)
throws|throws
name|IOException
block|{
name|graphics
operator|.
name|setComposite
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getNonStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|getNonStrokingPaint
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
name|linePath
operator|.
name|setWindingRule
argument_list|(
name|windingRule
argument_list|)
expr_stmt|;
comment|// disable anti-aliasing for rectangular paths, this is a workaround to avoid small stripes
comment|// which occur when solid fills are used to simulate piecewise gradients, see PDFBOX-2302
comment|// note that we ignore paths with a width/height under 1 as these are fills used as strokes,
comment|// see PDFBOX-1658 for an example
name|Rectangle2D
name|bounds
init|=
name|linePath
operator|.
name|getBounds2D
argument_list|()
decl_stmt|;
name|boolean
name|noAntiAlias
init|=
name|isRectangular
argument_list|(
name|linePath
argument_list|)
operator|&&
name|bounds
operator|.
name|getWidth
argument_list|()
operator|>
literal|1
operator|&&
name|bounds
operator|.
name|getHeight
argument_list|()
operator|>
literal|1
decl_stmt|;
if|if
condition|(
name|noAntiAlias
condition|)
block|{
name|graphics
operator|.
name|setRenderingHint
argument_list|(
name|RenderingHints
operator|.
name|KEY_ANTIALIASING
argument_list|,
name|RenderingHints
operator|.
name|VALUE_ANTIALIAS_OFF
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
operator|(
name|graphics
operator|.
name|getPaint
argument_list|()
operator|instanceof
name|Color
operator|)
condition|)
block|{
comment|// apply clip to path to avoid oversized device bounds in shading contexts (PDFBOX-2901)
name|Area
name|area
init|=
operator|new
name|Area
argument_list|(
name|linePath
argument_list|)
decl_stmt|;
name|area
operator|.
name|intersect
argument_list|(
operator|new
name|Area
argument_list|(
name|graphics
operator|.
name|getClip
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|fill
argument_list|(
name|area
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|graphics
operator|.
name|fill
argument_list|(
name|linePath
argument_list|)
expr_stmt|;
block|}
name|linePath
operator|.
name|reset
argument_list|()
expr_stmt|;
if|if
condition|(
name|noAntiAlias
condition|)
block|{
comment|// JDK 1.7 has a bug where rendering hints are reset by the above call to
comment|// the setRenderingHint method, so we re-set all hints, see PDFBOX-2302
name|setRenderingHints
argument_list|()
expr_stmt|;
block|}
block|}
comment|/**      * Returns true if the given path is rectangular.      */
specifier|private
name|boolean
name|isRectangular
parameter_list|(
name|GeneralPath
name|path
parameter_list|)
block|{
name|PathIterator
name|iter
init|=
name|path
operator|.
name|getPathIterator
argument_list|(
literal|null
argument_list|)
decl_stmt|;
name|double
index|[]
name|coords
init|=
operator|new
name|double
index|[
literal|6
index|]
decl_stmt|;
name|int
name|count
init|=
literal|0
decl_stmt|;
name|int
index|[]
name|xs
init|=
operator|new
name|int
index|[
literal|4
index|]
decl_stmt|;
name|int
index|[]
name|ys
init|=
operator|new
name|int
index|[
literal|4
index|]
decl_stmt|;
while|while
condition|(
operator|!
name|iter
operator|.
name|isDone
argument_list|()
condition|)
block|{
switch|switch
condition|(
name|iter
operator|.
name|currentSegment
argument_list|(
name|coords
argument_list|)
condition|)
block|{
case|case
name|PathIterator
operator|.
name|SEG_MOVETO
case|:
if|if
condition|(
name|count
operator|==
literal|0
condition|)
block|{
name|xs
index|[
name|count
index|]
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|coords
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
name|ys
index|[
name|count
index|]
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|coords
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
block|}
else|else
block|{
return|return
literal|false
return|;
block|}
name|count
operator|++
expr_stmt|;
break|break;
case|case
name|PathIterator
operator|.
name|SEG_LINETO
case|:
if|if
condition|(
name|count
operator|<
literal|4
condition|)
block|{
name|xs
index|[
name|count
index|]
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|coords
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
name|ys
index|[
name|count
index|]
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|coords
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
block|}
else|else
block|{
return|return
literal|false
return|;
block|}
name|count
operator|++
expr_stmt|;
break|break;
case|case
name|PathIterator
operator|.
name|SEG_CUBICTO
case|:
return|return
literal|false
return|;
case|case
name|PathIterator
operator|.
name|SEG_CLOSE
case|:
break|break;
block|}
name|iter
operator|.
name|next
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|count
operator|==
literal|4
condition|)
block|{
return|return
name|xs
index|[
literal|0
index|]
operator|==
name|xs
index|[
literal|1
index|]
operator|||
name|xs
index|[
literal|0
index|]
operator|==
name|xs
index|[
literal|2
index|]
operator|||
name|ys
index|[
literal|0
index|]
operator|==
name|ys
index|[
literal|1
index|]
operator|||
name|ys
index|[
literal|0
index|]
operator|==
name|ys
index|[
literal|3
index|]
return|;
block|}
return|return
literal|false
return|;
block|}
comment|/**      * Fills and then strokes the path.      *      * @param windingRule The winding rule this path will use.      * @throws IOException If there is an IO error while filling the path.      */
annotation|@
name|Override
specifier|public
name|void
name|fillAndStrokePath
parameter_list|(
name|int
name|windingRule
parameter_list|)
throws|throws
name|IOException
block|{
comment|// TODO can we avoid cloning the path?
name|GeneralPath
name|path
init|=
operator|(
name|GeneralPath
operator|)
name|linePath
operator|.
name|clone
argument_list|()
decl_stmt|;
name|fillPath
argument_list|(
name|windingRule
argument_list|)
expr_stmt|;
name|linePath
operator|=
name|path
expr_stmt|;
name|strokePath
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|clip
parameter_list|(
name|int
name|windingRule
parameter_list|)
block|{
comment|// the clipping path will not be updated until the succeeding painting operator is called
name|clipWindingRule
operator|=
name|windingRule
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|moveTo
parameter_list|(
name|float
name|x
parameter_list|,
name|float
name|y
parameter_list|)
block|{
name|linePath
operator|.
name|moveTo
argument_list|(
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|lineTo
parameter_list|(
name|float
name|x
parameter_list|,
name|float
name|y
parameter_list|)
block|{
name|linePath
operator|.
name|lineTo
argument_list|(
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|curveTo
parameter_list|(
name|float
name|x1
parameter_list|,
name|float
name|y1
parameter_list|,
name|float
name|x2
parameter_list|,
name|float
name|y2
parameter_list|,
name|float
name|x3
parameter_list|,
name|float
name|y3
parameter_list|)
block|{
name|linePath
operator|.
name|curveTo
argument_list|(
name|x1
argument_list|,
name|y1
argument_list|,
name|x2
argument_list|,
name|y2
argument_list|,
name|x3
argument_list|,
name|y3
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|Point2D
name|getCurrentPoint
parameter_list|()
block|{
return|return
name|linePath
operator|.
name|getCurrentPoint
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|closePath
parameter_list|()
block|{
name|linePath
operator|.
name|closePath
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|endPath
parameter_list|()
block|{
if|if
condition|(
name|clipWindingRule
operator|!=
operator|-
literal|1
condition|)
block|{
name|linePath
operator|.
name|setWindingRule
argument_list|(
name|clipWindingRule
argument_list|)
expr_stmt|;
name|getGraphicsState
argument_list|()
operator|.
name|intersectClippingPath
argument_list|(
name|linePath
argument_list|)
expr_stmt|;
name|clipWindingRule
operator|=
operator|-
literal|1
expr_stmt|;
block|}
name|linePath
operator|.
name|reset
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|drawImage
parameter_list|(
name|PDImage
name|pdImage
parameter_list|)
throws|throws
name|IOException
block|{
name|Matrix
name|ctm
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentTransformationMatrix
argument_list|()
decl_stmt|;
name|AffineTransform
name|at
init|=
name|ctm
operator|.
name|createAffineTransform
argument_list|()
decl_stmt|;
if|if
condition|(
operator|!
name|pdImage
operator|.
name|getInterpolate
argument_list|()
condition|)
block|{
name|boolean
name|isScaledUp
init|=
name|pdImage
operator|.
name|getWidth
argument_list|()
operator|<
name|Math
operator|.
name|round
argument_list|(
name|at
operator|.
name|getScaleX
argument_list|()
argument_list|)
operator|||
name|pdImage
operator|.
name|getHeight
argument_list|()
operator|<
name|Math
operator|.
name|round
argument_list|(
name|at
operator|.
name|getScaleY
argument_list|()
argument_list|)
decl_stmt|;
comment|// if the image is scaled down, we use smooth interpolation, eg PDFBOX-2364
comment|// only when scaled up do we use nearest neighbour, eg PDFBOX-2302 / mori-cvpr01.pdf
comment|// stencils are excluded from this rule (see survey.pdf)
if|if
condition|(
name|isScaledUp
operator|||
name|pdImage
operator|.
name|isStencil
argument_list|()
condition|)
block|{
name|graphics
operator|.
name|setRenderingHint
argument_list|(
name|RenderingHints
operator|.
name|KEY_INTERPOLATION
argument_list|,
name|RenderingHints
operator|.
name|VALUE_INTERPOLATION_NEAREST_NEIGHBOR
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
name|pdImage
operator|.
name|isStencil
argument_list|()
condition|)
block|{
comment|// fill the image with paint
name|BufferedImage
name|image
init|=
name|pdImage
operator|.
name|getStencilImage
argument_list|(
name|getNonStrokingPaint
argument_list|()
argument_list|)
decl_stmt|;
comment|// draw the image
name|drawBufferedImage
argument_list|(
name|image
argument_list|,
name|at
argument_list|)
expr_stmt|;
block|}
else|else
block|{
comment|// draw the image
name|drawBufferedImage
argument_list|(
name|pdImage
operator|.
name|getImage
argument_list|()
argument_list|,
name|at
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|pdImage
operator|.
name|getInterpolate
argument_list|()
condition|)
block|{
comment|// JDK 1.7 has a bug where rendering hints are reset by the above call to
comment|// the setRenderingHint method, so we re-set all hints, see PDFBOX-2302
name|setRenderingHints
argument_list|()
expr_stmt|;
block|}
block|}
specifier|private
name|void
name|drawBufferedImage
parameter_list|(
name|BufferedImage
name|image
parameter_list|,
name|AffineTransform
name|at
parameter_list|)
throws|throws
name|IOException
block|{
name|graphics
operator|.
name|setComposite
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getNonStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
name|PDSoftMask
name|softMask
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getSoftMask
argument_list|()
decl_stmt|;
if|if
condition|(
name|softMask
operator|!=
literal|null
condition|)
block|{
name|AffineTransform
name|imageTransform
init|=
operator|new
name|AffineTransform
argument_list|(
name|at
argument_list|)
decl_stmt|;
name|imageTransform
operator|.
name|scale
argument_list|(
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|imageTransform
operator|.
name|translate
argument_list|(
literal|0
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
name|Paint
name|awtPaint
init|=
operator|new
name|TexturePaint
argument_list|(
name|image
argument_list|,
operator|new
name|Rectangle2D
operator|.
name|Double
argument_list|(
name|imageTransform
operator|.
name|getTranslateX
argument_list|()
argument_list|,
name|imageTransform
operator|.
name|getTranslateY
argument_list|()
argument_list|,
name|imageTransform
operator|.
name|getScaleX
argument_list|()
argument_list|,
name|imageTransform
operator|.
name|getScaleY
argument_list|()
argument_list|)
argument_list|)
decl_stmt|;
name|awtPaint
operator|=
name|applySoftMaskToPaint
argument_list|(
name|awtPaint
argument_list|,
name|softMask
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|awtPaint
argument_list|)
expr_stmt|;
name|Rectangle2D
name|unitRect
init|=
operator|new
name|Rectangle2D
operator|.
name|Float
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
decl_stmt|;
name|graphics
operator|.
name|fill
argument_list|(
name|at
operator|.
name|createTransformedShape
argument_list|(
name|unitRect
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|COSBase
name|transfer
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getTransfer
argument_list|()
decl_stmt|;
if|if
condition|(
name|transfer
operator|instanceof
name|COSArray
operator|||
name|transfer
operator|instanceof
name|COSDictionary
condition|)
block|{
name|image
operator|=
name|applyTransferFunction
argument_list|(
name|image
argument_list|,
name|transfer
argument_list|)
expr_stmt|;
block|}
name|int
name|width
init|=
name|image
operator|.
name|getWidth
argument_list|(
literal|null
argument_list|)
decl_stmt|;
name|int
name|height
init|=
name|image
operator|.
name|getHeight
argument_list|(
literal|null
argument_list|)
decl_stmt|;
name|AffineTransform
name|imageTransform
init|=
operator|new
name|AffineTransform
argument_list|(
name|at
argument_list|)
decl_stmt|;
name|imageTransform
operator|.
name|scale
argument_list|(
literal|1.0
operator|/
name|width
argument_list|,
operator|-
literal|1.0
operator|/
name|height
argument_list|)
expr_stmt|;
name|imageTransform
operator|.
name|translate
argument_list|(
literal|0
argument_list|,
operator|-
name|height
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|drawImage
argument_list|(
name|image
argument_list|,
name|imageTransform
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
block|}
specifier|private
name|BufferedImage
name|applyTransferFunction
parameter_list|(
name|BufferedImage
name|image
parameter_list|,
name|COSBase
name|transfer
parameter_list|)
throws|throws
name|IOException
block|{
comment|// Deep copy http://stackoverflow.com/a/26894825/535646
name|ColorModel
name|cm
init|=
name|image
operator|.
name|getColorModel
argument_list|()
decl_stmt|;
name|boolean
name|isAlphaPremultiplied
init|=
name|cm
operator|.
name|isAlphaPremultiplied
argument_list|()
decl_stmt|;
name|WritableRaster
name|raster
init|=
name|image
operator|.
name|copyData
argument_list|(
name|image
operator|.
name|getRaster
argument_list|()
operator|.
name|createCompatibleWritableRaster
argument_list|()
argument_list|)
decl_stmt|;
name|BufferedImage
name|bim
init|=
operator|new
name|BufferedImage
argument_list|(
name|cm
argument_list|,
name|raster
argument_list|,
name|isAlphaPremultiplied
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|PDFunction
name|rf
decl_stmt|,
name|gf
decl_stmt|,
name|bf
decl_stmt|;
if|if
condition|(
name|transfer
operator|instanceof
name|COSArray
condition|)
block|{
name|COSArray
name|ar
init|=
operator|(
name|COSArray
operator|)
name|transfer
decl_stmt|;
name|rf
operator|=
name|PDFunction
operator|.
name|create
argument_list|(
name|ar
operator|.
name|getObject
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|gf
operator|=
name|PDFunction
operator|.
name|create
argument_list|(
name|ar
operator|.
name|getObject
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|bf
operator|=
name|PDFunction
operator|.
name|create
argument_list|(
name|ar
operator|.
name|getObject
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|rf
operator|=
name|gf
operator|=
name|bf
operator|=
name|PDFunction
operator|.
name|create
argument_list|(
name|transfer
argument_list|)
expr_stmt|;
block|}
name|float
name|input
index|[]
init|=
operator|new
name|float
index|[
literal|1
index|]
decl_stmt|;
for|for
control|(
name|int
name|x
init|=
literal|0
init|;
name|x
operator|<
name|image
operator|.
name|getWidth
argument_list|()
condition|;
operator|++
name|x
control|)
block|{
for|for
control|(
name|int
name|y
init|=
literal|0
init|;
name|y
operator|<
name|image
operator|.
name|getHeight
argument_list|()
condition|;
operator|++
name|y
control|)
block|{
name|int
name|rgb
init|=
name|image
operator|.
name|getRGB
argument_list|(
name|x
argument_list|,
name|y
argument_list|)
decl_stmt|;
name|input
index|[
literal|0
index|]
operator|=
operator|(
operator|(
name|rgb
operator|>>
literal|16
operator|)
operator|&
literal|0xFF
operator|)
operator|/
literal|255f
expr_stmt|;
name|int
name|r
init|=
call|(
name|int
call|)
argument_list|(
name|rf
operator|.
name|eval
argument_list|(
name|input
argument_list|)
index|[
literal|0
index|]
operator|*
literal|255
argument_list|)
decl_stmt|;
name|input
index|[
literal|0
index|]
operator|=
operator|(
operator|(
name|rgb
operator|>>
literal|8
operator|)
operator|&
literal|0xFF
operator|)
operator|/
literal|255f
expr_stmt|;
name|int
name|g
init|=
call|(
name|int
call|)
argument_list|(
name|gf
operator|.
name|eval
argument_list|(
name|input
argument_list|)
index|[
literal|0
index|]
operator|*
literal|255
argument_list|)
decl_stmt|;
name|input
index|[
literal|0
index|]
operator|=
operator|(
name|rgb
operator|&
literal|0xFF
operator|)
operator|/
literal|255f
expr_stmt|;
name|int
name|b
init|=
call|(
name|int
call|)
argument_list|(
name|bf
operator|.
name|eval
argument_list|(
name|input
argument_list|)
index|[
literal|0
index|]
operator|*
literal|255
argument_list|)
decl_stmt|;
name|bim
operator|.
name|setRGB
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
operator|(
name|rgb
operator|&
literal|0xFF000000
operator|)
operator||
operator|(
name|r
operator|<<
literal|16
operator|)
operator||
operator|(
name|g
operator|<<
literal|8
operator|)
operator||
name|b
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|bim
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|shadingFill
parameter_list|(
name|COSName
name|shadingName
parameter_list|)
throws|throws
name|IOException
block|{
name|PDShading
name|shading
init|=
name|getResources
argument_list|()
operator|.
name|getShading
argument_list|(
name|shadingName
argument_list|)
decl_stmt|;
name|Matrix
name|ctm
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentTransformationMatrix
argument_list|()
decl_stmt|;
name|Paint
name|paint
init|=
name|shading
operator|.
name|toPaint
argument_list|(
name|ctm
argument_list|)
decl_stmt|;
name|graphics
operator|.
name|setComposite
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getNonStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|paint
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setClip
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|lastClip
operator|=
literal|null
expr_stmt|;
name|graphics
operator|.
name|fill
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentClippingPath
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|showAnnotation
parameter_list|(
name|PDAnnotation
name|annotation
parameter_list|)
throws|throws
name|IOException
block|{
name|lastClip
operator|=
literal|null
expr_stmt|;
comment|//TODO support more annotation flags (Invisible, NoZoom, NoRotate)
comment|// Example for NoZoom can be found in p5 of PDFBOX-2348
name|int
name|deviceType
init|=
name|graphics
operator|.
name|getDeviceConfiguration
argument_list|()
operator|.
name|getDevice
argument_list|()
operator|.
name|getType
argument_list|()
decl_stmt|;
if|if
condition|(
name|deviceType
operator|==
name|GraphicsDevice
operator|.
name|TYPE_PRINTER
operator|&&
operator|!
name|annotation
operator|.
name|isPrinted
argument_list|()
condition|)
block|{
return|return;
block|}
if|if
condition|(
name|deviceType
operator|==
name|GraphicsDevice
operator|.
name|TYPE_RASTER_SCREEN
operator|&&
name|annotation
operator|.
name|isNoView
argument_list|()
condition|)
block|{
return|return;
block|}
if|if
condition|(
name|annotation
operator|.
name|isHidden
argument_list|()
condition|)
block|{
return|return;
block|}
name|super
operator|.
name|showAnnotation
argument_list|(
name|annotation
argument_list|)
expr_stmt|;
if|if
condition|(
name|annotation
operator|.
name|getAppearance
argument_list|()
operator|==
literal|null
condition|)
block|{
if|if
condition|(
name|annotation
operator|instanceof
name|PDAnnotationLink
condition|)
block|{
name|drawAnnotationLinkBorder
argument_list|(
operator|(
name|PDAnnotationLink
operator|)
name|annotation
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|annotation
operator|instanceof
name|PDAnnotationMarkup
operator|&&
name|annotation
operator|.
name|getSubtype
argument_list|()
operator|.
name|equals
argument_list|(
name|PDAnnotationMarkup
operator|.
name|SUB_TYPE_INK
argument_list|)
condition|)
block|{
name|drawAnnotationInk
argument_list|(
operator|(
name|PDAnnotationMarkup
operator|)
name|annotation
argument_list|)
expr_stmt|;
block|}
block|}
block|}
specifier|private
specifier|static
class|class
name|AnnotationBorder
block|{
specifier|private
name|float
index|[]
name|dashArray
init|=
literal|null
decl_stmt|;
specifier|private
name|boolean
name|underline
init|=
literal|false
decl_stmt|;
specifier|private
name|float
name|width
init|=
literal|0
decl_stmt|;
specifier|private
name|PDColor
name|color
decl_stmt|;
block|}
comment|// return border info. BorderStyle must be provided as parameter because
comment|// method is not available in the base class
specifier|private
name|AnnotationBorder
name|getAnnotationBorder
parameter_list|(
name|PDAnnotation
name|annotation
parameter_list|,
name|PDBorderStyleDictionary
name|borderStyle
parameter_list|)
block|{
name|AnnotationBorder
name|ab
init|=
operator|new
name|AnnotationBorder
argument_list|()
decl_stmt|;
name|COSArray
name|border
init|=
name|annotation
operator|.
name|getBorder
argument_list|()
decl_stmt|;
if|if
condition|(
name|borderStyle
operator|==
literal|null
condition|)
block|{
if|if
condition|(
name|border
operator|.
name|get
argument_list|(
literal|2
argument_list|)
operator|instanceof
name|COSNumber
condition|)
block|{
name|ab
operator|.
name|width
operator|=
operator|(
operator|(
name|COSNumber
operator|)
name|border
operator|.
name|getObject
argument_list|(
literal|2
argument_list|)
operator|)
operator|.
name|floatValue
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|border
operator|.
name|size
argument_list|()
operator|>
literal|3
condition|)
block|{
name|COSBase
name|base3
init|=
name|border
operator|.
name|getObject
argument_list|(
literal|3
argument_list|)
decl_stmt|;
if|if
condition|(
name|base3
operator|instanceof
name|COSArray
condition|)
block|{
name|ab
operator|.
name|dashArray
operator|=
operator|(
operator|(
name|COSArray
operator|)
name|base3
operator|)
operator|.
name|toFloatArray
argument_list|()
expr_stmt|;
block|}
block|}
block|}
else|else
block|{
name|ab
operator|.
name|width
operator|=
name|borderStyle
operator|.
name|getWidth
argument_list|()
expr_stmt|;
if|if
condition|(
name|borderStyle
operator|.
name|getStyle
argument_list|()
operator|.
name|equals
argument_list|(
name|PDBorderStyleDictionary
operator|.
name|STYLE_DASHED
argument_list|)
condition|)
block|{
name|ab
operator|.
name|dashArray
operator|=
name|borderStyle
operator|.
name|getDashStyle
argument_list|()
operator|.
name|getDashArray
argument_list|()
expr_stmt|;
block|}
if|if
condition|(
name|borderStyle
operator|.
name|getStyle
argument_list|()
operator|.
name|equals
argument_list|(
name|PDBorderStyleDictionary
operator|.
name|STYLE_UNDERLINE
argument_list|)
condition|)
block|{
name|ab
operator|.
name|underline
operator|=
literal|true
expr_stmt|;
block|}
block|}
name|ab
operator|.
name|color
operator|=
name|annotation
operator|.
name|getColor
argument_list|()
expr_stmt|;
if|if
condition|(
name|ab
operator|.
name|color
operator|==
literal|null
condition|)
block|{
comment|// spec is unclear, but black seems to be the right thing to do
name|ab
operator|.
name|color
operator|=
operator|new
name|PDColor
argument_list|(
operator|new
name|float
index|[]
block|{
literal|0
block|}
argument_list|,
name|PDDeviceGray
operator|.
name|INSTANCE
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|ab
operator|.
name|dashArray
operator|!=
literal|null
condition|)
block|{
name|boolean
name|allZero
init|=
literal|true
decl_stmt|;
for|for
control|(
name|float
name|f
range|:
name|ab
operator|.
name|dashArray
control|)
block|{
if|if
condition|(
name|f
operator|!=
literal|0
condition|)
block|{
name|allZero
operator|=
literal|false
expr_stmt|;
break|break;
block|}
block|}
if|if
condition|(
name|allZero
condition|)
block|{
name|ab
operator|.
name|dashArray
operator|=
literal|null
expr_stmt|;
block|}
block|}
return|return
name|ab
return|;
block|}
specifier|private
name|void
name|drawAnnotationLinkBorder
parameter_list|(
name|PDAnnotationLink
name|link
parameter_list|)
throws|throws
name|IOException
block|{
name|AnnotationBorder
name|ab
init|=
name|getAnnotationBorder
argument_list|(
name|link
argument_list|,
name|link
operator|.
name|getBorderStyle
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|ab
operator|.
name|width
operator|==
literal|0
condition|)
block|{
return|return;
block|}
name|PDRectangle
name|rectangle
init|=
name|link
operator|.
name|getRectangle
argument_list|()
decl_stmt|;
name|Stroke
name|oldStroke
init|=
name|graphics
operator|.
name|getStroke
argument_list|()
decl_stmt|;
name|graphics
operator|.
name|setPaint
argument_list|(
name|getPaint
argument_list|(
name|ab
operator|.
name|color
argument_list|)
argument_list|)
expr_stmt|;
name|BasicStroke
name|stroke
init|=
operator|new
name|BasicStroke
argument_list|(
name|ab
operator|.
name|width
argument_list|,
name|BasicStroke
operator|.
name|CAP_BUTT
argument_list|,
name|BasicStroke
operator|.
name|JOIN_MITER
argument_list|,
literal|10
argument_list|,
name|ab
operator|.
name|dashArray
argument_list|,
literal|0
argument_list|)
decl_stmt|;
name|graphics
operator|.
name|setStroke
argument_list|(
name|stroke
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setClip
argument_list|(
literal|null
argument_list|)
expr_stmt|;
if|if
condition|(
name|ab
operator|.
name|underline
condition|)
block|{
name|graphics
operator|.
name|drawLine
argument_list|(
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getLowerLeftX
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getLowerLeftY
argument_list|()
argument_list|,
call|(
name|int
call|)
argument_list|(
name|rectangle
operator|.
name|getLowerLeftX
argument_list|()
operator|+
name|rectangle
operator|.
name|getWidth
argument_list|()
argument_list|)
argument_list|,
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getLowerLeftY
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|graphics
operator|.
name|drawRect
argument_list|(
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getLowerLeftX
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getLowerLeftY
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getWidth
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|rectangle
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|graphics
operator|.
name|setStroke
argument_list|(
name|oldStroke
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|drawAnnotationInk
parameter_list|(
name|PDAnnotationMarkup
name|inkAnnotation
parameter_list|)
throws|throws
name|IOException
block|{
if|if
condition|(
operator|!
name|inkAnnotation
operator|.
name|getCOSObject
argument_list|()
operator|.
name|containsKey
argument_list|(
name|COSName
operator|.
name|INKLIST
argument_list|)
condition|)
block|{
return|return;
block|}
comment|//TODO there should be an InkAnnotation class with a getInkList method
name|COSBase
name|base
init|=
name|inkAnnotation
operator|.
name|getCOSObject
argument_list|()
operator|.
name|getDictionaryObject
argument_list|(
name|COSName
operator|.
name|INKLIST
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
operator|(
name|base
operator|instanceof
name|COSArray
operator|)
condition|)
block|{
return|return;
block|}
comment|// PDF spec does not mention /Border for ink annotations, but it is used if /BS is not available
name|AnnotationBorder
name|ab
init|=
name|getAnnotationBorder
argument_list|(
name|inkAnnotation
argument_list|,
name|inkAnnotation
operator|.
name|getBorderStyle
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|ab
operator|.
name|width
operator|==
literal|0
condition|)
block|{
return|return;
block|}
name|graphics
operator|.
name|setPaint
argument_list|(
name|getPaint
argument_list|(
name|ab
operator|.
name|color
argument_list|)
argument_list|)
expr_stmt|;
name|Stroke
name|oldStroke
init|=
name|graphics
operator|.
name|getStroke
argument_list|()
decl_stmt|;
name|BasicStroke
name|stroke
init|=
operator|new
name|BasicStroke
argument_list|(
name|ab
operator|.
name|width
argument_list|,
name|BasicStroke
operator|.
name|CAP_BUTT
argument_list|,
name|BasicStroke
operator|.
name|JOIN_MITER
argument_list|,
literal|10
argument_list|,
name|ab
operator|.
name|dashArray
argument_list|,
literal|0
argument_list|)
decl_stmt|;
name|graphics
operator|.
name|setStroke
argument_list|(
name|stroke
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|setClip
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|COSArray
name|pathsArray
init|=
operator|(
name|COSArray
operator|)
name|base
decl_stmt|;
for|for
control|(
name|COSBase
name|baseElement
range|:
operator|(
name|Iterable
argument_list|<
name|?
extends|extends
name|COSBase
argument_list|>
operator|)
name|pathsArray
operator|.
name|toList
argument_list|()
control|)
block|{
if|if
condition|(
operator|!
operator|(
name|baseElement
operator|instanceof
name|COSArray
operator|)
condition|)
block|{
continue|continue;
block|}
name|COSArray
name|pathArray
init|=
operator|(
name|COSArray
operator|)
name|baseElement
decl_stmt|;
name|int
name|nPoints
init|=
name|pathArray
operator|.
name|size
argument_list|()
operator|/
literal|2
decl_stmt|;
comment|// "When drawn, the points shall be connected by straight lines or curves
comment|// in an implementation-dependent way" - we do lines.
name|GeneralPath
name|path
init|=
operator|new
name|GeneralPath
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|nPoints
condition|;
operator|++
name|i
control|)
block|{
name|COSBase
name|bx
init|=
name|pathArray
operator|.
name|getObject
argument_list|(
name|i
operator|*
literal|2
argument_list|)
decl_stmt|;
name|COSBase
name|by
init|=
name|pathArray
operator|.
name|getObject
argument_list|(
name|i
operator|*
literal|2
operator|+
literal|1
argument_list|)
decl_stmt|;
if|if
condition|(
name|bx
operator|instanceof
name|COSNumber
operator|&&
name|by
operator|instanceof
name|COSNumber
condition|)
block|{
name|float
name|x
init|=
operator|(
operator|(
name|COSNumber
operator|)
name|bx
operator|)
operator|.
name|floatValue
argument_list|()
decl_stmt|;
name|float
name|y
init|=
operator|(
operator|(
name|COSNumber
operator|)
name|by
operator|)
operator|.
name|floatValue
argument_list|()
decl_stmt|;
if|if
condition|(
name|i
operator|==
literal|0
condition|)
block|{
name|path
operator|.
name|moveTo
argument_list|(
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|path
operator|.
name|lineTo
argument_list|(
name|x
argument_list|,
name|y
argument_list|)
expr_stmt|;
block|}
block|}
block|}
name|graphics
operator|.
name|draw
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
name|graphics
operator|.
name|setStroke
argument_list|(
name|oldStroke
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|showTransparencyGroup
parameter_list|(
name|PDTransparencyGroup
name|form
parameter_list|)
throws|throws
name|IOException
block|{
name|TransparencyGroup
name|group
init|=
operator|new
name|TransparencyGroup
argument_list|(
name|form
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|graphics
operator|.
name|setComposite
argument_list|(
name|getGraphicsState
argument_list|()
operator|.
name|getNonStrokingJavaComposite
argument_list|()
argument_list|)
expr_stmt|;
name|setClip
argument_list|()
expr_stmt|;
comment|// both the DPI xform and the CTM were already applied to the group, so all we do
comment|// here is draw it directly onto the Graphics2D device at the appropriate position
name|PDRectangle
name|bbox
init|=
name|group
operator|.
name|getBBox
argument_list|()
decl_stmt|;
name|AffineTransform
name|prev
init|=
name|graphics
operator|.
name|getTransform
argument_list|()
decl_stmt|;
name|float
name|x
init|=
name|bbox
operator|.
name|getLowerLeftX
argument_list|()
decl_stmt|;
name|float
name|y
init|=
name|pageSize
operator|.
name|getHeight
argument_list|()
operator|-
name|bbox
operator|.
name|getLowerLeftY
argument_list|()
operator|-
name|bbox
operator|.
name|getHeight
argument_list|()
decl_stmt|;
name|graphics
operator|.
name|setTransform
argument_list|(
name|AffineTransform
operator|.
name|getTranslateInstance
argument_list|(
name|x
operator|*
name|xform
operator|.
name|getScaleX
argument_list|()
argument_list|,
name|y
operator|*
name|xform
operator|.
name|getScaleY
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|PDSoftMask
name|softMask
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getSoftMask
argument_list|()
decl_stmt|;
if|if
condition|(
name|softMask
operator|!=
literal|null
condition|)
block|{
name|BufferedImage
name|image
init|=
name|group
operator|.
name|getImage
argument_list|()
decl_stmt|;
name|Paint
name|awtPaint
init|=
operator|new
name|TexturePaint
argument_list|(
name|image
argument_list|,
operator|new
name|Rectangle2D
operator|.
name|Float
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|image
operator|.
name|getWidth
argument_list|()
argument_list|,
name|image
operator|.
name|getHeight
argument_list|()
argument_list|)
argument_list|)
decl_stmt|;
name|awtPaint
operator|=
name|applySoftMaskToPaint
argument_list|(
name|awtPaint
argument_list|,
name|softMask
argument_list|)
expr_stmt|;
comment|// todo: PDFBOX-994 problem here?
name|graphics
operator|.
name|setPaint
argument_list|(
name|awtPaint
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|fill
argument_list|(
operator|new
name|Rectangle2D
operator|.
name|Float
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|bbox
operator|.
name|getWidth
argument_list|()
operator|*
operator|(
name|float
operator|)
name|xform
operator|.
name|getScaleX
argument_list|()
argument_list|,
name|bbox
operator|.
name|getHeight
argument_list|()
operator|*
operator|(
name|float
operator|)
name|xform
operator|.
name|getScaleY
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|graphics
operator|.
name|drawImage
argument_list|(
name|group
operator|.
name|getImage
argument_list|()
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
name|graphics
operator|.
name|setTransform
argument_list|(
name|prev
argument_list|)
expr_stmt|;
block|}
comment|/**      * Transparency group.      **/
specifier|private
specifier|final
class|class
name|TransparencyGroup
block|{
specifier|private
specifier|final
name|BufferedImage
name|image
decl_stmt|;
specifier|private
specifier|final
name|PDRectangle
name|bbox
decl_stmt|;
specifier|private
specifier|final
name|int
name|minX
decl_stmt|;
specifier|private
specifier|final
name|int
name|minY
decl_stmt|;
specifier|private
specifier|final
name|int
name|width
decl_stmt|;
specifier|private
specifier|final
name|int
name|height
decl_stmt|;
comment|/**          * Creates a buffered image for a transparency group result.          */
specifier|private
name|TransparencyGroup
parameter_list|(
name|PDTransparencyGroup
name|form
parameter_list|,
name|boolean
name|isSoftMask
parameter_list|)
throws|throws
name|IOException
block|{
name|Graphics2D
name|g2dOriginal
init|=
name|graphics
decl_stmt|;
name|Area
name|lastClipOriginal
init|=
name|lastClip
decl_stmt|;
comment|// get the CTM x Form Matrix transform
name|Matrix
name|ctm
init|=
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentTransformationMatrix
argument_list|()
decl_stmt|;
name|Matrix
name|transform
init|=
name|Matrix
operator|.
name|concatenate
argument_list|(
name|ctm
argument_list|,
name|form
operator|.
name|getMatrix
argument_list|()
argument_list|)
decl_stmt|;
comment|// transform the bbox
name|GeneralPath
name|transformedBox
init|=
name|form
operator|.
name|getBBox
argument_list|()
operator|.
name|transform
argument_list|(
name|transform
argument_list|)
decl_stmt|;
comment|// clip the bbox to prevent giant bboxes from consuming all memory
name|Area
name|clip
init|=
operator|(
name|Area
operator|)
name|getGraphicsState
argument_list|()
operator|.
name|getCurrentClippingPath
argument_list|()
operator|.
name|clone
argument_list|()
decl_stmt|;
name|clip
operator|.
name|intersect
argument_list|(
operator|new
name|Area
argument_list|(
name|transformedBox
argument_list|)
argument_list|)
expr_stmt|;
name|Rectangle2D
name|clipRect
init|=
name|clip
operator|.
name|getBounds2D
argument_list|()
decl_stmt|;
name|this
operator|.
name|bbox
operator|=
operator|new
name|PDRectangle
argument_list|(
operator|(
name|float
operator|)
name|clipRect
operator|.
name|getX
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|clipRect
operator|.
name|getY
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|clipRect
operator|.
name|getWidth
argument_list|()
argument_list|,
operator|(
name|float
operator|)
name|clipRect
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
comment|// apply the underlying Graphics2D device's DPI transform
name|Shape
name|deviceClip
init|=
name|xform
operator|.
name|createTransformedShape
argument_list|(
name|clip
argument_list|)
decl_stmt|;
name|Rectangle2D
name|bounds
init|=
name|deviceClip
operator|.
name|getBounds2D
argument_list|()
decl_stmt|;
name|minX
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|bounds
operator|.
name|getMinX
argument_list|()
argument_list|)
expr_stmt|;
name|minY
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|bounds
operator|.
name|getMinY
argument_list|()
argument_list|)
expr_stmt|;
name|int
name|maxX
init|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|bounds
operator|.
name|getMaxX
argument_list|()
argument_list|)
operator|+
literal|1
decl_stmt|;
name|int
name|maxY
init|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|bounds
operator|.
name|getMaxY
argument_list|()
argument_list|)
operator|+
literal|1
decl_stmt|;
name|width
operator|=
name|maxX
operator|-
name|minX
expr_stmt|;
name|height
operator|=
name|maxY
operator|-
name|minY
expr_stmt|;
name|image
operator|=
operator|new
name|BufferedImage
argument_list|(
name|width
argument_list|,
name|height
argument_list|,
name|BufferedImage
operator|.
name|TYPE_INT_ARGB
argument_list|)
expr_stmt|;
comment|// FIXME - color space
name|Graphics2D
name|g
init|=
name|image
operator|.
name|createGraphics
argument_list|()
decl_stmt|;
comment|// flip y-axis
name|g
operator|.
name|translate
argument_list|(
literal|0
argument_list|,
name|height
argument_list|)
expr_stmt|;
name|g
operator|.
name|scale
argument_list|(
literal|1
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|// apply device transform (DPI)
name|g
operator|.
name|transform
argument_list|(
name|xform
argument_list|)
expr_stmt|;
comment|// adjust the origin
name|g
operator|.
name|translate
argument_list|(
operator|-
name|clipRect
operator|.
name|getX
argument_list|()
argument_list|,
operator|-
name|clipRect
operator|.
name|getY
argument_list|()
argument_list|)
expr_stmt|;
name|graphics
operator|=
name|g
expr_stmt|;
try|try
block|{
if|if
condition|(
name|isSoftMask
condition|)
block|{
name|processSoftMask
argument_list|(
name|form
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|processTransparencyGroup
argument_list|(
name|form
argument_list|)
expr_stmt|;
block|}
block|}
finally|finally
block|{
name|lastClip
operator|=
name|lastClipOriginal
expr_stmt|;
name|graphics
operator|.
name|dispose
argument_list|()
expr_stmt|;
name|graphics
operator|=
name|g2dOriginal
expr_stmt|;
block|}
block|}
specifier|public
name|BufferedImage
name|getImage
parameter_list|()
block|{
return|return
name|image
return|;
block|}
specifier|public
name|PDRectangle
name|getBBox
parameter_list|()
block|{
return|return
name|bbox
return|;
block|}
specifier|public
name|Raster
name|getAlphaRaster
parameter_list|()
block|{
return|return
name|image
operator|.
name|getAlphaRaster
argument_list|()
return|;
block|}
specifier|public
name|Raster
name|getLuminosityRaster
parameter_list|()
block|{
name|BufferedImage
name|gray
init|=
operator|new
name|BufferedImage
argument_list|(
name|width
argument_list|,
name|height
argument_list|,
name|BufferedImage
operator|.
name|TYPE_BYTE_GRAY
argument_list|)
decl_stmt|;
name|Graphics
name|g
init|=
name|gray
operator|.
name|getGraphics
argument_list|()
decl_stmt|;
name|g
operator|.
name|drawImage
argument_list|(
name|image
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|g
operator|.
name|dispose
argument_list|()
expr_stmt|;
return|return
name|gray
operator|.
name|getRaster
argument_list|()
return|;
block|}
block|}
block|}
end_class

end_unit

