begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|rendering
package|;
end_package

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Color
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|Graphics2D
import|;
end_import

begin_import
import|import
name|java
operator|.
name|awt
operator|.
name|image
operator|.
name|BufferedImage
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|cos
operator|.
name|COSName
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDDocument
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDPage
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|PDResources
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|common
operator|.
name|PDRectangle
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|blend
operator|.
name|BlendMode
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|graphics
operator|.
name|state
operator|.
name|PDExtendedGraphicsState
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|AnnotationFilter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|pdfbox
operator|.
name|pdmodel
operator|.
name|interactive
operator|.
name|annotation
operator|.
name|PDAnnotation
import|;
end_import

begin_comment
comment|/**  * Renders a PDF document to an AWT BufferedImage.  * This class may be overridden in order to perform custom rendering.  *  * @author John Hewson  */
end_comment

begin_class
specifier|public
class|class
name|PDFRenderer
block|{
specifier|protected
specifier|final
name|PDDocument
name|document
decl_stmt|;
comment|// TODO keep rendering state such as caches here
comment|/**     * Default annotations filter, returns all annotations     */
specifier|private
name|AnnotationFilter
name|annotationFilter
init|=
operator|new
name|AnnotationFilter
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|boolean
name|accept
parameter_list|(
name|PDAnnotation
name|annotation
parameter_list|)
block|{
return|return
literal|true
return|;
block|}
block|}
decl_stmt|;
specifier|private
name|boolean
name|subsamplingAllowed
init|=
literal|false
decl_stmt|;
specifier|private
name|BufferedImage
name|pageImage
decl_stmt|;
comment|/**      * Creates a new PDFRenderer.      * @param document the document to render      */
specifier|public
name|PDFRenderer
parameter_list|(
name|PDDocument
name|document
parameter_list|)
block|{
name|this
operator|.
name|document
operator|=
name|document
expr_stmt|;
block|}
comment|/**      * Return the AnnotationFilter.      *       * @return the AnnotationFilter      */
specifier|public
name|AnnotationFilter
name|getAnnotationsFilter
parameter_list|()
block|{
return|return
name|annotationFilter
return|;
block|}
comment|/**      * Set the AnnotationFilter.      *       *<p>Allows to only render annotation accepted by the filter.      *       * @param annotationsFilter the AnnotationFilter      */
specifier|public
name|void
name|setAnnotationsFilter
parameter_list|(
name|AnnotationFilter
name|annotationsFilter
parameter_list|)
block|{
name|this
operator|.
name|annotationFilter
operator|=
name|annotationsFilter
expr_stmt|;
block|}
comment|/**      * Value indicating if the renderer is allowed to subsample images before drawing, according to      * image dimensions and requested scale.      *      * Subsampling may be faster and less memory-intensive in some cases, but it may also lead to      * loss of quality, especially in images with high spatial frequency.      *      * @return true if subsampling of images is allowed, false otherwise.      */
specifier|public
name|boolean
name|isSubsamplingAllowed
parameter_list|()
block|{
return|return
name|subsamplingAllowed
return|;
block|}
comment|/**      * Sets a value instructing the renderer whether it is allowed to subsample images before      * drawing. The subsampling frequency is determined according to image size and requested scale.      *      * Subsampling may be faster and less memory-intensive in some cases, but it may also lead to      * loss of quality, especially in images with high spatial frequency.      *      * @param subsamplingAllowed The new value indicating if subsampling is allowed.      */
specifier|public
name|void
name|setSubsamplingAllowed
parameter_list|(
name|boolean
name|subsamplingAllowed
parameter_list|)
block|{
name|this
operator|.
name|subsamplingAllowed
operator|=
name|subsamplingAllowed
expr_stmt|;
block|}
comment|/**      * Returns the given page as an RGB image at 72 DPI      * @param pageIndex the zero-based index of the page to be converted.      * @return the rendered page image      * @throws IOException if the PDF cannot be read      */
specifier|public
name|BufferedImage
name|renderImage
parameter_list|(
name|int
name|pageIndex
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|renderImage
argument_list|(
name|pageIndex
argument_list|,
literal|1
argument_list|)
return|;
block|}
comment|/**      * Returns the given page as an RGB image at the given scale.      * A scale of 1 will render at 72 DPI.      * @param pageIndex the zero-based index of the page to be converted      * @param scale the scaling factor, where 1 = 72 DPI      * @return the rendered page image      * @throws IOException if the PDF cannot be read      */
specifier|public
name|BufferedImage
name|renderImage
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|float
name|scale
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|renderImage
argument_list|(
name|pageIndex
argument_list|,
name|scale
argument_list|,
name|ImageType
operator|.
name|RGB
argument_list|)
return|;
block|}
comment|/**      * Returns the given page as an RGB image at the given DPI.      * @param pageIndex the zero-based index of the page to be converted      * @param dpi the DPI (dots per inch) to render at      * @return the rendered page image      * @throws IOException if the PDF cannot be read      */
specifier|public
name|BufferedImage
name|renderImageWithDPI
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|float
name|dpi
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|renderImage
argument_list|(
name|pageIndex
argument_list|,
name|dpi
operator|/
literal|72f
argument_list|,
name|ImageType
operator|.
name|RGB
argument_list|)
return|;
block|}
comment|/**      * Returns the given page as an RGB image at the given DPI.      * @param pageIndex the zero-based index of the page to be converted      * @param dpi the DPI (dots per inch) to render at      * @param imageType the type of image to return      * @return the rendered page image      * @throws IOException if the PDF cannot be read      */
specifier|public
name|BufferedImage
name|renderImageWithDPI
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|float
name|dpi
parameter_list|,
name|ImageType
name|imageType
parameter_list|)
throws|throws
name|IOException
block|{
return|return
name|renderImage
argument_list|(
name|pageIndex
argument_list|,
name|dpi
operator|/
literal|72f
argument_list|,
name|imageType
argument_list|)
return|;
block|}
comment|/**      * Returns the given page as an RGB or ARGB image at the given scale.      * @param pageIndex the zero-based index of the page to be converted      * @param scale the scaling factor, where 1 = 72 DPI      * @param imageType the type of image to return      * @return the rendered page image      * @throws IOException if the PDF cannot be read      */
specifier|public
name|BufferedImage
name|renderImage
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|float
name|scale
parameter_list|,
name|ImageType
name|imageType
parameter_list|)
throws|throws
name|IOException
block|{
name|PDPage
name|page
init|=
name|document
operator|.
name|getPage
argument_list|(
name|pageIndex
argument_list|)
decl_stmt|;
name|PDRectangle
name|cropbBox
init|=
name|page
operator|.
name|getCropBox
argument_list|()
decl_stmt|;
name|float
name|widthPt
init|=
name|cropbBox
operator|.
name|getWidth
argument_list|()
decl_stmt|;
name|float
name|heightPt
init|=
name|cropbBox
operator|.
name|getHeight
argument_list|()
decl_stmt|;
name|int
name|widthPx
init|=
name|Math
operator|.
name|round
argument_list|(
name|widthPt
operator|*
name|scale
argument_list|)
decl_stmt|;
name|int
name|heightPx
init|=
name|Math
operator|.
name|round
argument_list|(
name|heightPt
operator|*
name|scale
argument_list|)
decl_stmt|;
name|int
name|rotationAngle
init|=
name|page
operator|.
name|getRotation
argument_list|()
decl_stmt|;
name|int
name|bimType
init|=
name|imageType
operator|.
name|toBufferedImageType
argument_list|()
decl_stmt|;
if|if
condition|(
name|imageType
operator|!=
name|ImageType
operator|.
name|ARGB
operator|&&
name|hasBlendMode
argument_list|(
name|page
argument_list|)
condition|)
block|{
comment|// PDFBOX-4095: if the PDF has blending on the top level, draw on transparent background
comment|// Inpired from PDF.js: if a PDF page uses any blend modes other than Normal,
comment|// PDF.js renders everything on a fully transparent RGBA canvas.
comment|// Finally when the page has been rendered, PDF.js draws the RGBA canvas on a white canvas.
name|bimType
operator|=
name|BufferedImage
operator|.
name|TYPE_INT_ARGB
expr_stmt|;
block|}
comment|// swap width and height
name|BufferedImage
name|image
decl_stmt|;
if|if
condition|(
name|rotationAngle
operator|==
literal|90
operator|||
name|rotationAngle
operator|==
literal|270
condition|)
block|{
name|image
operator|=
operator|new
name|BufferedImage
argument_list|(
name|heightPx
argument_list|,
name|widthPx
argument_list|,
name|bimType
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|image
operator|=
operator|new
name|BufferedImage
argument_list|(
name|widthPx
argument_list|,
name|heightPx
argument_list|,
name|bimType
argument_list|)
expr_stmt|;
block|}
name|pageImage
operator|=
name|image
expr_stmt|;
comment|// use a transparent background if the image type supports alpha
name|Graphics2D
name|g
init|=
name|image
operator|.
name|createGraphics
argument_list|()
decl_stmt|;
if|if
condition|(
name|image
operator|.
name|getType
argument_list|()
operator|==
name|BufferedImage
operator|.
name|TYPE_INT_ARGB
condition|)
block|{
name|g
operator|.
name|setBackground
argument_list|(
operator|new
name|Color
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|g
operator|.
name|setBackground
argument_list|(
name|Color
operator|.
name|WHITE
argument_list|)
expr_stmt|;
block|}
name|g
operator|.
name|clearRect
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|image
operator|.
name|getWidth
argument_list|()
argument_list|,
name|image
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
name|transform
argument_list|(
name|g
argument_list|,
name|page
argument_list|,
name|scale
argument_list|,
name|scale
argument_list|)
expr_stmt|;
comment|// the end-user may provide a custom PageDrawer
name|PageDrawerParameters
name|parameters
init|=
operator|new
name|PageDrawerParameters
argument_list|(
name|this
argument_list|,
name|page
argument_list|,
name|subsamplingAllowed
argument_list|)
decl_stmt|;
name|PageDrawer
name|drawer
init|=
name|createPageDrawer
argument_list|(
name|parameters
argument_list|)
decl_stmt|;
name|drawer
operator|.
name|drawPage
argument_list|(
name|g
argument_list|,
name|page
operator|.
name|getCropBox
argument_list|()
argument_list|)
expr_stmt|;
name|g
operator|.
name|dispose
argument_list|()
expr_stmt|;
if|if
condition|(
name|image
operator|.
name|getType
argument_list|()
operator|!=
name|imageType
operator|.
name|toBufferedImageType
argument_list|()
condition|)
block|{
comment|// PDFBOX-4095: draw temporary transparent image on white background
name|BufferedImage
name|newImage
init|=
operator|new
name|BufferedImage
argument_list|(
name|image
operator|.
name|getWidth
argument_list|()
argument_list|,
name|image
operator|.
name|getHeight
argument_list|()
argument_list|,
name|imageType
operator|.
name|toBufferedImageType
argument_list|()
argument_list|)
decl_stmt|;
name|Graphics2D
name|dstGraphics
init|=
name|newImage
operator|.
name|createGraphics
argument_list|()
decl_stmt|;
name|dstGraphics
operator|.
name|setBackground
argument_list|(
name|Color
operator|.
name|WHITE
argument_list|)
expr_stmt|;
name|dstGraphics
operator|.
name|clearRect
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|image
operator|.
name|getWidth
argument_list|()
argument_list|,
name|image
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
name|dstGraphics
operator|.
name|drawImage
argument_list|(
name|image
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|null
argument_list|)
expr_stmt|;
name|dstGraphics
operator|.
name|dispose
argument_list|()
expr_stmt|;
name|image
operator|=
name|newImage
expr_stmt|;
block|}
return|return
name|image
return|;
block|}
comment|/**      * Renders a given page to an AWT Graphics2D instance.      * @param pageIndex the zero-based index of the page to be converted      * @param graphics the Graphics2D on which to draw the page      * @throws IOException if the PDF cannot be read      */
specifier|public
name|void
name|renderPageToGraphics
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|Graphics2D
name|graphics
parameter_list|)
throws|throws
name|IOException
block|{
name|renderPageToGraphics
argument_list|(
name|pageIndex
argument_list|,
name|graphics
argument_list|,
literal|1
argument_list|)
expr_stmt|;
block|}
comment|/**      * Renders a given page to an AWT Graphics2D instance.      * @param pageIndex the zero-based index of the page to be converted      * @param graphics the Graphics2D on which to draw the page      * @param scale the scale to draw the page at      * @throws IOException if the PDF cannot be read      */
specifier|public
name|void
name|renderPageToGraphics
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|Graphics2D
name|graphics
parameter_list|,
name|float
name|scale
parameter_list|)
throws|throws
name|IOException
block|{
name|renderPageToGraphics
argument_list|(
name|pageIndex
argument_list|,
name|graphics
argument_list|,
name|scale
argument_list|,
name|scale
argument_list|)
expr_stmt|;
block|}
comment|/**      * Renders a given page to an AWT Graphics2D instance.      *       * @param pageIndex the zero-based index of the page to be converted      * @param graphics the Graphics2D on which to draw the page      * @param scaleX the scale to draw the page at for the x-axis      * @param scaleY the scale to draw the page at for the y-axis      * @throws IOException if the PDF cannot be read      */
specifier|public
name|void
name|renderPageToGraphics
parameter_list|(
name|int
name|pageIndex
parameter_list|,
name|Graphics2D
name|graphics
parameter_list|,
name|float
name|scaleX
parameter_list|,
name|float
name|scaleY
parameter_list|)
throws|throws
name|IOException
block|{
name|PDPage
name|page
init|=
name|document
operator|.
name|getPage
argument_list|(
name|pageIndex
argument_list|)
decl_stmt|;
comment|// TODO need width/wight calculations? should these be in PageDrawer?
name|transform
argument_list|(
name|graphics
argument_list|,
name|page
argument_list|,
name|scaleX
argument_list|,
name|scaleY
argument_list|)
expr_stmt|;
name|PDRectangle
name|cropBox
init|=
name|page
operator|.
name|getCropBox
argument_list|()
decl_stmt|;
name|graphics
operator|.
name|clearRect
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
operator|(
name|int
operator|)
name|cropBox
operator|.
name|getWidth
argument_list|()
argument_list|,
operator|(
name|int
operator|)
name|cropBox
operator|.
name|getHeight
argument_list|()
argument_list|)
expr_stmt|;
comment|// the end-user may provide a custom PageDrawer
name|PageDrawerParameters
name|parameters
init|=
operator|new
name|PageDrawerParameters
argument_list|(
name|this
argument_list|,
name|page
argument_list|,
name|subsamplingAllowed
argument_list|)
decl_stmt|;
name|PageDrawer
name|drawer
init|=
name|createPageDrawer
argument_list|(
name|parameters
argument_list|)
decl_stmt|;
name|drawer
operator|.
name|drawPage
argument_list|(
name|graphics
argument_list|,
name|cropBox
argument_list|)
expr_stmt|;
block|}
comment|// scale rotate translate
specifier|private
name|void
name|transform
parameter_list|(
name|Graphics2D
name|graphics
parameter_list|,
name|PDPage
name|page
parameter_list|,
name|float
name|scaleX
parameter_list|,
name|float
name|scaleY
parameter_list|)
block|{
name|graphics
operator|.
name|scale
argument_list|(
name|scaleX
argument_list|,
name|scaleY
argument_list|)
expr_stmt|;
comment|// TODO should we be passing the scale to PageDrawer rather than messing with Graphics?
name|int
name|rotationAngle
init|=
name|page
operator|.
name|getRotation
argument_list|()
decl_stmt|;
name|PDRectangle
name|cropBox
init|=
name|page
operator|.
name|getCropBox
argument_list|()
decl_stmt|;
if|if
condition|(
name|rotationAngle
operator|!=
literal|0
condition|)
block|{
name|float
name|translateX
init|=
literal|0
decl_stmt|;
name|float
name|translateY
init|=
literal|0
decl_stmt|;
switch|switch
condition|(
name|rotationAngle
condition|)
block|{
case|case
literal|90
case|:
name|translateX
operator|=
name|cropBox
operator|.
name|getHeight
argument_list|()
expr_stmt|;
break|break;
case|case
literal|270
case|:
name|translateY
operator|=
name|cropBox
operator|.
name|getWidth
argument_list|()
expr_stmt|;
break|break;
case|case
literal|180
case|:
name|translateX
operator|=
name|cropBox
operator|.
name|getWidth
argument_list|()
expr_stmt|;
name|translateY
operator|=
name|cropBox
operator|.
name|getHeight
argument_list|()
expr_stmt|;
break|break;
default|default:
break|break;
block|}
name|graphics
operator|.
name|translate
argument_list|(
name|translateX
argument_list|,
name|translateY
argument_list|)
expr_stmt|;
name|graphics
operator|.
name|rotate
argument_list|(
operator|(
name|float
operator|)
name|Math
operator|.
name|toRadians
argument_list|(
name|rotationAngle
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Returns a new PageDrawer instance, using the given parameters. May be overridden.      */
specifier|protected
name|PageDrawer
name|createPageDrawer
parameter_list|(
name|PageDrawerParameters
name|parameters
parameter_list|)
throws|throws
name|IOException
block|{
name|PageDrawer
name|pageDrawer
init|=
operator|new
name|PageDrawer
argument_list|(
name|parameters
argument_list|)
decl_stmt|;
name|pageDrawer
operator|.
name|setAnnotationFilter
argument_list|(
name|annotationFilter
argument_list|)
expr_stmt|;
return|return
name|pageDrawer
return|;
block|}
specifier|private
name|boolean
name|hasBlendMode
parameter_list|(
name|PDPage
name|page
parameter_list|)
block|{
comment|// check the current resources for blend modes
name|PDResources
name|resources
init|=
name|page
operator|.
name|getResources
argument_list|()
decl_stmt|;
if|if
condition|(
name|resources
operator|==
literal|null
condition|)
block|{
return|return
literal|false
return|;
block|}
for|for
control|(
name|COSName
name|name
range|:
name|resources
operator|.
name|getExtGStateNames
argument_list|()
control|)
block|{
name|PDExtendedGraphicsState
name|extGState
init|=
name|resources
operator|.
name|getExtGState
argument_list|(
name|name
argument_list|)
decl_stmt|;
if|if
condition|(
name|extGState
operator|==
literal|null
condition|)
block|{
comment|// can happen if key exists but no value
comment|// see PDFBOX-3950-23EGDHXSBBYQLKYOKGZUOVYVNE675PRD.pdf
continue|continue;
block|}
name|BlendMode
name|blendMode
init|=
name|extGState
operator|.
name|getBlendMode
argument_list|()
decl_stmt|;
if|if
condition|(
name|blendMode
operator|!=
name|BlendMode
operator|.
name|NORMAL
condition|)
block|{
return|return
literal|true
return|;
block|}
block|}
return|return
literal|false
return|;
block|}
comment|/**      * Returns the image to which the current page is being rendered.      * May be null if the page is rendered to a Graphics2D object      * instead of a BufferedImage.      */
name|BufferedImage
name|getPageImage
parameter_list|()
block|{
return|return
name|pageImage
return|;
block|}
block|}
end_class

end_unit

